/**
 * This file is AUTO-GENERATED by extract_assets.cjs.
 * DO NOT EDIT MANUALLY.
 * Run 'npm run extract-assets' to regenerate.
 */

export type FantasyPanelVariant = 'wood' | 'paper' | 'stone' | 'gold' | 'obsidian';
export type FantasyContainerVariant = 'book_open';
export type FantasyTabVariant = 'red' | 'blue' | 'green' | 'yellow';

export const FANTASY_UI_CONFIG = {
    "panels": {
        "wood": {
            "top": 10,
            "right": 10,
            "bottom": 10,
            "left": 10
        },
        "paper": {
            "top": 10,
            "right": 10,
            "bottom": 10,
            "left": 10
        },
        "stone": {
            "top": 10,
            "right": 10,
            "bottom": 10,
            "left": 10
        },
        "gold": {
            "top": 10,
            "right": 10,
            "bottom": 10,
            "left": 10
        },
        "obsidian": {
            "top": 10,
            "right": 10,
            "bottom": 10,
            "left": 10
        }
    }
} as const;
