/**
 * CLASS-EXCLUSIVE UPGRADES
 * Fase 1: Alle nye upgrades som BARE én klasse kan kjøpe.
 *
 * Extends UpgradeConfig med:
 *   classRestriction: ClassId   – alltid satt (aldri undefined her)
 *   isAbilityUpgrade?: boolean  – true = påvirker class-ability direkte
 *
 * Kategorier per klasse:
 *   Krieger  → DRIVKRAFT / MASTRING / KAMPTALENT / RUSTNING
 *   Archer   → DRIVKRAFT / MASTRING / TALENTER / SMIDIGHET
 *   Wizard   → DRIVKRAFT / MASTRING / SYNERGI / ARKAN KUNNSKAP
 */

import type { UpgradeConfig } from './upgrades';
import type { ClassId } from './classes';

export interface ClassUpgradeConfig extends UpgradeConfig {
    classRestriction: ClassId;
    isAbilityUpgrade?: boolean;
    shopCategoryId: string;
}

// ─── KRIEGER ─────────────────────────────────────────────────────────────────

/** Krieger SVERD: Whirlwind Slash ability-nivåer + legendaries */
const KRIEGER_DRIVKRAFT: ClassUpgradeConfig[] = [
    {
        id: 'whirl_damage',
        title: 'Skarpe Kniver',
        icon: 'item_sword',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_virvelvind',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Øker skaden til virvelvind',
        value: { suffix: '%', getValue: (lvl) => 100 + lvl * 25 },
        maxLevel: 3,
        basePrice: 200,
        priceScale: 2.2,
        iconTint: 'drop-shadow(0 0 5px #cc4400) hue-rotate(-10deg)',
        requires: { unlock_whirlwind: 1 },
    },
    {
        id: 'whirl_cooldown',
        title: 'Rotasjonsfart',
        icon: 'item_swords_crossed',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_virvelvind',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Reduserer ventetid på virvelvind',
        value: { suffix: 's', isReduction: true, getValue: (lvl) => [6.4, 5.1, 4.1][lvl - 1] ?? 8 },
        maxLevel: 3,
        basePrice: 250,
        priceScale: 2.5,
        iconTint: 'drop-shadow(0 0 5px #cc4400) hue-rotate(-10deg)',
        requires: { whirl_damage: 1 },
    },
    {
        id: 'whirl_chain',
        title: 'Eksplosiv Sekvens',
        icon: 'item_swords_crossed',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_virvelvind',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Treff med virvelvind reduserer ventetid ytterligere',
        value: { prefix: '-', suffix: '% CD', getValue: (lvl) => lvl === 1 ? 25 : 35 },
        maxLevel: 2,
        basePrice: 500,
        priceScale: 2.8,
        iconTint: 'drop-shadow(0 0 5px #cc4400) hue-rotate(-10deg)',
        requires: { whirl_cooldown: 2 },
    },
    {
        id: 'berserker_rage',
        title: 'Berserkerfurie',
        icon: 'item_sword_heavy',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_sverd',
        chapterId: 'combat_style',
        summary: 'Gjør mer skade når du har lav helse',
        value: { prefix: '+', suffix: '% skade', getValue: (lvl) => lvl * 5 },
        maxLevel: 3,
        basePrice: 300,
        priceScale: 2.5,
        iconTint: 'drop-shadow(0 0 5px #cc4400) hue-rotate(-10deg)',
    },
    {
        id: 'livsstaling',
        title: 'Livsstaling',
        icon: 'item_potion_red',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_sverd',
        chapterId: 'combat_style',
        summary: 'Gjenoppretter helse ved fiendedrap i nærkamp',
        value: { prefix: '+', suffix: ' HP', getValue: (lvl) => lvl * 8 },
        maxLevel: 4,
        basePrice: 200,
        priceScale: 2.0,
    },
    {
        id: 'blodust',
        title: 'Blodtorne',
        icon: 'item_shield',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_sverd',
        chapterId: 'combat_style',
        summary: 'Returnerer deler av skaden til fienden',
        value: { suffix: '% retur', getValue: (lvl) => lvl * 15 },
        maxLevel: 3,
        basePrice: 350,
        priceScale: 2.8,
        requires: { armor: 3 },
    },
];

/** Krieger SVERD – Grunnlag (ekstra) */
const KRIEGER_MASTRING_NYE: ClassUpgradeConfig[] = [
    {
        id: 'wide_swing',
        title: 'Bred Svingning',
        icon: 'item_sword',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_sverd',
        chapterId: 'foundation',
        summary: 'Øker rekkevidden på sverdangrep',
        value: { prefix: '+', suffix: '% bue', getValue: (lvl) => lvl * 30 },
        maxLevel: 3,
        basePrice: 180,
        priceScale: 2.0,
    },
    {
        id: 'heavy_momentum',
        title: 'Tyngdekraft',
        icon: 'item_sword_heavy',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_sverd',
        chapterId: 'foundation',
        summary: 'Hvert treff øker skaden på neste slag',
        value: { prefix: '+', suffix: '% skade', getValue: (lvl) => lvl * 10 },
        maxLevel: 3,
        basePrice: 250,
        priceScale: 2.3,
    },
];

/** Krieger SVERD – Kampstil */
const KRIEGER_KAMPTALENT: ClassUpgradeConfig[] = [
    {
        id: 'counter_strike',
        title: 'Kontraangrep',
        icon: 'item_swords_crossed',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_sverd',
        chapterId: 'combat_style',
        summary: 'Sjanse for å returnere skade ved treff',
        value: { prefix: '+', suffix: '% sjanse', getValue: (lvl) => lvl * 20 },
        maxLevel: 3,
        basePrice: 300,
        priceScale: 2.5,
        requires: { armor: 2 },
    },
    {
        id: 'stomp',
        title: 'Stormtramp',
        icon: 'item_sword_heavy',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_sverd',
        chapterId: 'combat_style',
        summary: 'Etter dash: mini-AoE stun rundt spilleren',
        value: { suffix: ' sek', getValue: (lvl) => lvl === 1 ? 0.5 : 0.8 },
        maxLevel: 2,
        basePrice: 400,
        priceScale: 3.0,
        requires: { dash_cooldown: 2 },
    },
    {
        id: 'battle_cry',
        title: 'Krigsrop',
        icon: 'item_swords_crossed',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_sverd',
        chapterId: 'combat_style',
        summary: 'Drap trigger midlertidig skadebonus',
        value: { prefix: '+', suffix: '% skade', getValue: (lvl) => lvl * 15 },
        maxLevel: 3,
        basePrice: 280,
        priceScale: 2.4,
    },
    {
        id: 'executioner',
        title: 'Bøddel',
        icon: 'item_sword',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_sverd',
        chapterId: 'combat_style',
        summary: 'Økt skade mot fiender med lav helse',
        value: { prefix: '+', suffix: '% skade', getValue: (lvl) => lvl * 50 },
        maxLevel: 2,
        basePrice: 450,
        priceScale: 2.8,
        requires: { damage: 5 },
    },
];

/** Krieger RUSTNING – Defense-synergier */
const KRIEGER_RUSTNING: ClassUpgradeConfig[] = [
    {
        id: 'skadeskalering',
        title: 'Skadeskalering',
        icon: 'item_shield',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_rustning',
        chapterId: 'combat_style',
        summary: 'Øker skade basert på rustning',
        value: { prefix: '+', suffix: '% skade', getValue: (lvl) => lvl * 5 },
        maxLevel: 3,
        basePrice: 220,
        priceScale: 2.2,
        requires: { armor: 3 },
    },
    {
        id: 'utstotbar_slag',
        title: 'Utstøtbar Slag',
        icon: 'item_sword_heavy',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_rustning',
        chapterId: 'combat_style',
        summary: 'Fiender som blir dyttet bort skader hverandre',
        value: { suffix: '% eks.skade', getValue: (lvl) => lvl > 0 ? 40 : 0 },
        maxLevel: 2,
        basePrice: 500,
        priceScale: 3.0,
        requires: { knockback: 5 },
    },
    {
        id: 'iron_will',
        title: 'Jernvilje',
        icon: 'item_shield',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_rustning',
        chapterId: 'foundation',
        summary: 'Overlev dødelig skade med 1 HP',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 800,
        priceScale: 1.0,
        requires: { armor: 6 },
        iconTint: 'drop-shadow(0 0 6px #aaccff) brightness(1.3)',
    },
    {
        id: 'fortification',
        title: 'Befestning',
        icon: 'item_shield',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_rustning',
        chapterId: 'combat_style',
        summary: 'Stå stille for rustningsbonus (avtar over tid)',
        value: { prefix: '+', suffix: '% rustning', getValue: (lvl) => lvl * 20 },
        maxLevel: 3,
        basePrice: 200,
        priceScale: 2.0,
    },
];

/** Krieger KROK – Kjettingkrok (hotkey 4) ability-oppgraderinger */
const KRIEGER_KROK: ClassUpgradeConfig[] = [
    {
        id: 'grapple_cooldown',
        title: 'Herdet Lenke',
        icon: 'item_hook_chain',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_krok',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Reduserer ventetid på Kjettingkrok',
        value: { prefix: '-', suffix: ' sek', getValue: (lvl) => lvl },
        maxLevel: 3,
        basePrice: 200,
        priceScale: 2.0,
        iconTint: 'drop-shadow(0 0 4px #888) brightness(1.1)',
        requires: { unlock_grapple: 1 },
    },
    {
        id: 'grapple_radius',
        title: 'Bredere Kast',
        icon: 'item_hook_chain',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_krok',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Øker rekkevidden på Kjettingkrok',
        value: { prefix: '+', suffix: '%', getValue: (lvl) => lvl * 25 },
        maxLevel: 3,
        basePrice: 250,
        priceScale: 2.2,
        iconTint: 'drop-shadow(0 0 4px #888) brightness(1.1)',
    },
    {
        id: 'grapple_damage',
        title: 'Jerngrep',
        icon: 'item_hook_chain',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_krok',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Dratte fiender tar skade ved landing',
        value: { prefix: '+', suffix: ' skade', getValue: (lvl) => lvl * 75 },
        maxLevel: 3,
        basePrice: 350,
        priceScale: 2.4,
        iconTint: 'drop-shadow(0 0 4px #cc4400) hue-rotate(-10deg)',
    },
    {
        id: 'grapple_stun',
        title: 'Ramtalt',
        icon: 'item_hook_chain',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_krok',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Dratte fiender er stunnet 1s ved landing',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 600,
        priceScale: 1.0,
        requires: { grapple_damage: 2 },
        iconTint: 'drop-shadow(0 0 6px #cc4400) hue-rotate(-10deg) brightness(1.2)',
        // TODO: leses av GrappleAbility-logikk i main.ts
    },
    {
        id: 'grapple_lifesteal',
        title: 'Vampyriske Lenker',
        icon: 'item_hook_chain',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_krok',
        chapterId: 'combat_style',
        summary: 'Helbreder basert på grapple-skade',
        value: { prefix: '+', suffix: '%', getValue: (lvl) => lvl * 15 },
        maxLevel: 2,
        basePrice: 450,
        priceScale: 2.6,
        iconTint: 'drop-shadow(0 0 5px #cc0000) hue-rotate(0deg)',
    },
    {
        id: 'grapple_chain',
        title: 'Dobbel Krok',
        icon: 'item_hook_chain',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_krok',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Kaster to kroker — doblet effektareal',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 900,
        priceScale: 1.0,
        requires: { grapple_radius: 2 },
        iconTint: 'drop-shadow(0 0 8px #ffaa00) brightness(1.4)',
        // TODO: leses av GrappleAbility-logikk i main.ts
    },
];

// ─── ARCHER ──────────────────────────────────────────────────────────────────

/** Archer BUE: Phantom Volley ability-nivåer + presisjon */
const ARCHER_DRIVKRAFT: ClassUpgradeConfig[] = [
    {
        id: 'volley_count',
        title: 'Pilregn',
        icon: 'item_bow',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_fantombyge',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Øker antall piler i Fantombyge',
        value: { prefix: '+', suffix: ' piler', getValue: (lvl) => lvl * 5 },
        maxLevel: 3,
        basePrice: 220,
        priceScale: 2.3,
        iconTint: 'drop-shadow(0 0 5px #ff6600) hue-rotate(20deg)',
        requires: { unlock_explosive: 1 },
    },
    {
        id: 'volley_damage',
        title: 'Fantomkraft',
        icon: 'item_crossbow',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_fantombyge',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Øker skaden til hver pil i Fantombyge',
        value: { suffix: 'x skade', getValue: (lvl) => (1.0 + lvl * 0.2).toFixed(1) },
        maxLevel: 3,
        basePrice: 250,
        priceScale: 2.5,
        iconTint: 'drop-shadow(0 0 5px #ff6600) hue-rotate(20deg)',
        requires: { volley_count: 1 },
    },
    {
        id: 'volley_pierce',
        title: 'Nådeløs Byge',
        icon: 'item_crossbow',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_fantombyge',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Piler fra Fantombyge går gjennom flere fiender',
        value: { prefix: '+', suffix: ' pierce', getValue: (lvl) => lvl },
        maxLevel: 2,
        basePrice: 550,
        priceScale: 3.0,
        iconTint: 'drop-shadow(0 0 5px #ff6600) hue-rotate(20deg)',
        requires: { volley_damage: 2 },
    },
    {
        id: 'rikosjett',
        title: 'Rikosjett',
        icon: 'item_bow',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_bue',
        chapterId: 'combat_style',
        summary: 'Piler spretter til nye mål',
        value: { suffix: ' mål', getValue: (lvl) => lvl },
        maxLevel: 3,
        basePrice: 300,
        priceScale: 2.5,
    },
    {
        id: 'fokusert_skudd',
        title: 'Fokusert Skudd',
        icon: 'item_bow',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_bue',
        chapterId: 'combat_style',
        summary: 'Lad bue for kraftigere piercende skudd',
        value: { suffix: 'x skade', getValue: (lvl) => lvl === 1 ? 2.0 : 2.5 },
        maxLevel: 2,
        basePrice: 500,
        priceScale: 2.8,
        requires: { arrow_damage: 4 },
    },
    {
        id: 'shadeskudd',
        title: 'Skuddkaskade',
        icon: 'item_bow',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_bue',
        chapterId: 'combat_style',
        summary: 'Eksplosjons-drap genererer ekstra piler',
        value: { suffix: ' piler', getValue: (lvl) => lvl },
        maxLevel: 3,
        basePrice: 280,
        priceScale: 2.3,
        requires: { multishot: 2 },
    },
];

/** Archer BUE – Presisjon (talenter) */
const ARCHER_TALENTER: ClassUpgradeConfig[] = [
    {
        id: 'headshot',
        title: 'Hodeskudd',
        icon: 'item_bow',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_bue',
        chapterId: 'combat_style',
        summary: 'Økt sjanse for kritiske treff med piler',
        value: { prefix: '+', suffix: '% sjanse', getValue: (lvl) => lvl * 15 },
        maxLevel: 3,
        basePrice: 200,
        priceScale: 2.2,
        requires: { crit_chance: 2 },
    },
    {
        id: 'eagle_eye',
        title: 'Ørneøye',
        icon: 'item_bow',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_bue',
        chapterId: 'combat_style',
        summary: 'Øker pilhastighet og rekkevidde',
        value: { prefix: '+', suffix: '% fart', getValue: (lvl) => lvl * 30 },
        maxLevel: 3,
        basePrice: 250,
        priceScale: 2.4,
        requires: { arrow_speed: 3 },
    },
    {
        id: 'pindown',
        title: 'Festepil',
        icon: 'item_bow',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_bue',
        chapterId: 'combat_style',
        summary: 'Sjanse for at piler stopper fiender',
        value: { suffix: ' sek', getValue: (lvl) => 0.5 + lvl },
        maxLevel: 3,
        basePrice: 350,
        priceScale: 2.7,
        requires: { pierce: 1 },
    },
    {
        id: 'time_slow_arrow',
        title: 'Tempopil',
        icon: 'item_bow',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_bue',
        chapterId: 'combat_style',
        summary: 'Spesialpil som bremser alle fiender',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 700,
        priceScale: 1.0,
        requires: { eagle_eye: 2 },
        iconTint: 'drop-shadow(0 0 6px #00ccff) hue-rotate(160deg)',
    },
];

/** Archer SMIDIGHET – Mobilitet */
const ARCHER_SMIDIGHET: ClassUpgradeConfig[] = [
    {
        id: 'luftmobilitet',
        title: 'Luftmobilitet',
        icon: 'item_lightning',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_smidighet',
        summary: 'Øker antall tilgjengelige dash',
        value: { suffix: ' totalt', getValue: (lvl) => 2 + lvl },
        maxLevel: 2,
        basePrice: 350,
        priceScale: 3.0,
    },
    {
        id: 'aerial_shot',
        title: 'Luftskudd',
        icon: 'item_bow',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_smidighet',
        summary: 'Mulighet til å skyte under dash uten fartsreduksjon',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 2,
        basePrice: 300,
        priceScale: 2.8,
    },
    {
        id: 'shadow_step',
        title: 'Skyggetrinn',
        icon: 'item_lightning',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_smidighet',
        summary: 'Midlertidig usynlighet etter dash',
        value: { suffix: ' sek', getValue: (lvl) => lvl === 1 ? 0.5 : 1 },
        maxLevel: 2,
        basePrice: 400,
        priceScale: 3.0,
    },
    {
        id: 'kite_mastery',
        title: 'Dragemanøver',
        icon: 'item_lightning',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_smidighet',
        summary: 'Drap reduserer ventetid på dash umiddelbart',
        value: { prefix: '-', suffix: '% CD', getValue: (lvl) => lvl * 20 },
        maxLevel: 3,
        basePrice: 220,
        priceScale: 2.2,
    },
];

/** Archer HOPP OG BYGE – Vault ability-oppgraderinger (slot 3) */
const ARCHER_VAULT: ClassUpgradeConfig[] = [
    {
        id: 'vault_arrows',
        title: 'Stormbyge',
        icon: 'item_lightning',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_vault',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Øker antall piler i viftesalven etter hopp',
        value: { prefix: '+', suffix: ' piler', getValue: (lvl) => lvl * 2 },
        maxLevel: 3,
        basePrice: 200,
        priceScale: 2.2,
        iconTint: 'drop-shadow(0 0 5px #88ccff) hue-rotate(160deg)',
        requires: { unlock_vault: 1 },
    },
    {
        id: 'vault_damage',
        title: 'Viftestyrke',
        icon: 'item_lightning',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_vault',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Øker skaden til vault-pilene',
        value: { prefix: '+', suffix: '% skade', getValue: (lvl) => lvl * 25 },
        maxLevel: 3,
        basePrice: 250,
        priceScale: 2.4,
        iconTint: 'drop-shadow(0 0 5px #88ccff) hue-rotate(160deg)',
        requires: { vault_arrows: 1 },
    },
    {
        id: 'vault_distance',
        title: 'Kraftig Hopp',
        icon: 'item_lightning',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_vault',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Øker hoppavstanden bakover',
        value: { prefix: '+', suffix: '% avstand', getValue: (lvl) => lvl * 30 },
        maxLevel: 3,
        basePrice: 180,
        priceScale: 2.0,
        iconTint: 'drop-shadow(0 0 5px #88ccff) hue-rotate(160deg)',
    },
    {
        id: 'vault_cooldown',
        title: 'Akrobatisk Tempo',
        icon: 'item_lightning',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_vault',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Reduserer ventetid på Hopp og Byge',
        value: { suffix: 's', isReduction: true, getValue: (lvl) => [5.5, 4.5, 3.5][lvl - 1] ?? 7 },
        maxLevel: 3,
        basePrice: 280,
        priceScale: 2.5,
        iconTint: 'drop-shadow(0 0 5px #88ccff) hue-rotate(160deg)',
        requires: { vault_arrows: 1 },
    },
    {
        id: 'vault_pierce',
        title: 'Gjennomtrengende Vifte',
        icon: 'item_lightning',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_vault',
        chapterId: 'combat_style',
        isAbilityUpgrade: true,
        summary: 'Vault-piler piercer gjennom fiender',
        value: { prefix: '+', suffix: ' pierce', getValue: (lvl) => lvl },
        maxLevel: 2,
        basePrice: 550,
        priceScale: 3.0,
        iconTint: 'drop-shadow(0 0 6px #aaddff) hue-rotate(160deg) brightness(1.3)',
        requires: { vault_damage: 2 },
    },
];

/** Archer SKYGGEMANNEKENG – Decoy ability-oppgraderinger (slot 4) */
const ARCHER_DECOY: ClassUpgradeConfig[] = [
    {
        id: 'decoy_duration',
        title: 'Lengre Lokkefugl',
        icon: 'item_phantom',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_decoy',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Øker varigheten på Skyggemannekeng',
        value: { prefix: '+', suffix: ' sek', getValue: (lvl) => lvl * 2 },
        maxLevel: 3,
        basePrice: 200,
        priceScale: 2.1,
        iconTint: 'drop-shadow(0 0 5px #6644aa) hue-rotate(240deg)',
        requires: { unlock_decoy: 1 },
    },
    {
        id: 'decoy_invis',
        title: 'Dypere Skygge',
        icon: 'item_phantom',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_decoy',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Øker usynlighetstiden etter plassering',
        value: { prefix: '+', suffix: ' sek', getValue: (lvl) => lvl * 1 },
        maxLevel: 3,
        basePrice: 250,
        priceScale: 2.3,
        iconTint: 'drop-shadow(0 0 5px #6644aa) hue-rotate(240deg)',
        requires: { decoy_duration: 1 },
    },
    {
        id: 'decoy_cooldown',
        title: 'Rask Bytte',
        icon: 'item_phantom',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_decoy',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Reduserer ventetid på Skyggemannekeng',
        value: { suffix: 's', isReduction: true, getValue: (lvl) => [12, 9, 7][lvl - 1] ?? 15 },
        maxLevel: 3,
        basePrice: 300,
        priceScale: 2.5,
        iconTint: 'drop-shadow(0 0 5px #6644aa) hue-rotate(240deg)',
        requires: { decoy_duration: 1 },
    },
    {
        id: 'decoy_mimic',
        title: 'Falsk Skygge',
        icon: 'item_phantom',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_decoy',
        chapterId: 'combat_style',
        summary: 'Lokkefuglen skyter tilbake mot nærmeste fiende',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 500,
        priceScale: 1.0,
        requires: { decoy_duration: 2 },
        iconTint: 'drop-shadow(0 0 6px #aa77dd) hue-rotate(240deg) brightness(1.2)',
    },
    {
        id: 'decoy_explode',
        title: 'Selvdestruering',
        icon: 'item_phantom',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_decoy',
        chapterId: 'combat_style',
        summary: 'Lokkefuglen eksploderer og skader fiender når den ødelegges',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 800,
        priceScale: 1.0,
        requires: { decoy_duration: 2, decoy_mimic: 1 },
        iconTint: 'drop-shadow(0 0 8px #cc55ff) hue-rotate(240deg) brightness(1.4)',
    },
];

// ─── WIZARD ──────────────────────────────────────────────────────────────────

/** Wizard EVNER: Arcane Cascade ability-nivåer + legendaries */
const WIZARD_DRIVKRAFT: ClassUpgradeConfig[] = [
    {
        id: 'cascade_duration',
        title: 'Mørk Materie',
        icon: 'item_magic_staff',
        category: 'Magi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_kaskade',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Øker varigheten på Arcane Cascade',
        value: { suffix: ' sek', getValue: (lvl: number) => 3 + lvl * 0.5 },
        maxLevel: 3,
        basePrice: 250,
        priceScale: 2.4,
        iconTint: 'drop-shadow(0 0 5px #8800ff) hue-rotate(200deg)',
        requires: { unlock_cascade: 1 },
    },
    {
        id: 'cascade_radius',
        title: 'Hendelseshorisont',
        icon: 'item_magic_staff',
        category: 'Magi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_kaskade',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Øker draradius til Arcane Cascade',
        value: { prefix: '+', suffix: '%', getValue: (lvl: number) => lvl * 25 },
        maxLevel: 3,
        basePrice: 280,
        priceScale: 2.5,
        iconTint: 'drop-shadow(0 0 5px #8800ff) hue-rotate(200deg)',
        requires: { cascade_duration: 1 },
    },
    {
        id: 'cascade_damage',
        title: 'Knusende Gravitasjon',
        icon: 'item_lightning_staff',
        category: 'Magi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_kaskade',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Eksplosjonen gjør mer skade i sentrum',
        value: { prefix: '+', suffix: '%', getValue: (lvl: number) => lvl * 50 },
        maxLevel: 2,
        basePrice: 600,
        priceScale: 3.0,
        iconTint: 'drop-shadow(0 0 5px #8800ff) hue-rotate(200deg)',
        requires: { cascade_radius: 2 },
    },
    {
        id: 'manaring',
        title: 'Manaring',
        icon: 'item_frost_orb',
        category: 'Magi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_kaskade',
        chapterId: 'ability',
        summary: 'Aktiv Kaskade gir skadereduksjon',
        value: { suffix: '%', getValue: (lvl: number) => lvl === 1 ? 25 : 40 },
        maxLevel: 2,
        basePrice: 450,
        priceScale: 2.8,
        requires: { cascade_duration: 2 },
    },
    {
        id: 'elementar_overfload',
        title: 'Elementær Overflod',
        icon: 'item_magic_staff',
        category: 'Magi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_evner',
        chapterId: 'combat_style',
        summary: 'Bruk av trolldom øker skaden til andre trolldommer',
        value: { prefix: '+', suffix: '% skade', getValue: (lvl) => lvl * 10 },
        maxLevel: 3,
        basePrice: 320,
        priceScale: 2.6,
    },
    {
        id: 'nullifikasjon',
        title: 'Magisk Nullifikasjon',
        icon: 'item_frost_orb',
        category: 'Magi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_kaskade',
        chapterId: 'ability',
        summary: 'Egen trolldom kan ødelegge innkommende bolter',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 900,
        priceScale: 1.0,
        requires: { cascade_damage: 1 },
        iconTint: 'drop-shadow(0 0 8px #8800ff) hue-rotate(200deg) brightness(1.3)',
    },
];

/** Wizard SYNERGI – Trolldomsinteraksjoner */
const WIZARD_SYNERGI: ClassUpgradeConfig[] = [
    {
        id: 'frozen_lightning',
        title: 'Frosset Torden',
        icon: 'item_lightning_staff',
        category: 'Synergi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_synergi',
        summary: 'Frosne fiender truffet av lyn splintres',
        value: { prefix: 'x', suffix: ' skade', getValue: (lvl) => lvl > 0 ? 4 : 1 },
        maxLevel: 1,
        basePrice: 700,
        priceScale: 1.0,
        requires: { frost_shatter: 2, lightning_stun: 3 },
        iconTint: 'drop-shadow(0 0 6px #8800ff) hue-rotate(200deg)',
    },
    {
        id: 'blaze_storm',
        title: 'Ildstorm',
        icon: 'item_magic_staff',
        category: 'Synergi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_synergi',
        summary: 'Kombinasjon av ild og lyn lager midlertidig brannfelt',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 2,
        basePrice: 600,
        priceScale: 2.5,
        requires: { fire_chain: 2, lightning_damage: 5 },
        iconTint: 'drop-shadow(0 0 6px #8800ff) hue-rotate(200deg)',
    },
    {
        id: 'absolute_zero',
        title: 'Absolutt Null',
        icon: 'item_frost_orb',
        category: 'Synergi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_synergi',
        summary: 'Frosne fiender kan kastes mot andre fiender',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 1000,
        priceScale: 1.0,
        requires: { frost_slow: 5, cascade_duration: 2 },
        iconTint: 'drop-shadow(0 0 6px #8800ff) hue-rotate(200deg)',
    },
];

/** Wizard ILDMAGI – Ekstra massiv eksplosjon */
const WIZARD_MASTRING_NYE: ClassUpgradeConfig[] = [
    {
        id: 'massiv_eksplosjon',
        title: 'Massiv Eksplosjon',
        icon: 'item_magic_staff',
        category: 'Magi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_ild',
        summary: 'Større rekkevidde på ildkuler',
        value: { prefix: '+', suffix: 'px radius', getValue: (lvl) => lvl * 40 },
        maxLevel: 2,
        basePrice: 500,
        priceScale: 2.5,
    },
];

/** Wizard EVNER – Avanserte trolldomsteknikker */
const WIZARD_ARKAN: ClassUpgradeConfig[] = [
    {
        id: 'spell_echo',
        title: 'Trolldomseko',
        icon: 'item_magic_staff',
        category: 'Magi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_evner',
        chapterId: 'combat_style',
        summary: 'Sjanse for å kaste trolldom uten ventetid',
        value: { suffix: '% sjanse', getValue: (lvl) => lvl * 15 },
        maxLevel: 3,
        basePrice: 300,
        priceScale: 2.5,
    },
    {
        id: 'overload',
        title: 'Overbelastning',
        icon: 'item_lightning_staff',
        category: 'Magi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_evner',
        chapterId: 'combat_style',
        summary: 'Treffer 3 fiender gir gratis neste kast',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 2,
        basePrice: 400,
        priceScale: 2.8,
        requires: { spell_echo: 2 },
    },
    {
        id: 'arcane_insight',
        title: 'Arkan Innsikt',
        icon: 'item_magic_staff',
        category: 'Magi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_evner',
        chapterId: 'combat_style',
        summary: 'Hvert 4. kast reduserer ventetid på trolldom',
        value: { prefix: '-', suffix: '% CD', getValue: (lvl) => lvl * 30 },
        maxLevel: 3,
        basePrice: 350,
        priceScale: 2.6,
    },
    {
        id: 'mana_shield',
        title: 'Manadel',
        icon: 'item_frost_orb',
        category: 'Magi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_evner',
        chapterId: 'combat_style',
        summary: 'Sjanse for å absorbere skade med ventetid-reduksjon',
        value: { prefix: '+', suffix: '% sjanse', getValue: (lvl) => lvl * 30 },
        maxLevel: 2,
        basePrice: 500,
        priceScale: 3.0,
        requires: { armor: 2 },
    },
];

// ─── SKALD ───────────────────────────────────────────────────────────────────

/** Skald KVAD: Vers-skalering, Stridssang, Kvad-utbrudd */
const SKALD_KVAD: ClassUpgradeConfig[] = [
    // ─── Harpe (Hotkey 1) Base Attack Upgrades ───────────────────────────
    {
        id: 'harpe_damage',
        title: 'Harpens Kraft',
        icon: 'item_harp',
        category: 'Kvad',
        classRestriction: 'skald',
        shopCategoryId: 'skald_harpe',
        chapterId: 'foundation',
        summary: 'Øker skaden til Harpe',
        value: { prefix: '+', suffix: '% skade', getValue: (lvl) => lvl * 20 },
        maxLevel: 3,
        basePrice: 160,
        priceScale: 1.9,
    },
    {
        id: 'harpe_speed',
        title: 'Rask Streng',
        icon: 'item_harp',
        category: 'Kvad',
        classRestriction: 'skald',
        shopCategoryId: 'skald_harpe',
        chapterId: 'foundation',
        summary: 'Øker angrepshastighet for Harpe',
        value: { prefix: '+', suffix: '% fart', getValue: (lvl) => lvl * 15 },
        maxLevel: 3,
        basePrice: 180,
        priceScale: 2.0,
    },
    {
        id: 'harpe_pierce',
        title: 'Gjennomtrengende Tone',
        icon: 'item_spear',
        category: 'Kvad',
        classRestriction: 'skald',
        shopCategoryId: 'skald_harpe',
        chapterId: 'foundation',
        summary: 'Harpe går gjennom fiender',
        value: { prefix: '+', suffix: ' pierce', getValue: (lvl) => lvl },
        maxLevel: 2,
        basePrice: 300,
        priceScale: 2.5,
        requires: { harpe_damage: 2 },
    },

    // ─── Vers Scaling & Violin (Hotkey 2) ──────────────────────────
    {
        id: 'vers_damage',
        title: 'Versets Kraft',
        icon: 'item_lute',
        category: 'Kvad',
        classRestriction: 'skald',
        shopCategoryId: 'skald_vers',
        chapterId: 'foundation',
        summary: 'Hvert Vers øker skaden',
        value: { prefix: '+', suffix: '% per vers', getValue: (lvl) => lvl * 15 },
        maxLevel: 3,
        basePrice: 200,
        priceScale: 2.2,
    },
    {
        id: 'sonic_damage',
        title: 'Stridssangens Kraft',
        icon: 'item_harp',
        category: 'Kvad',
        classRestriction: 'skald',
        shopCategoryId: 'skald_fiolin',
        chapterId: 'foundation',
        summary: 'Øker skaden til Stridssang',
        value: { prefix: '+', suffix: '% skade', getValue: (lvl) => lvl * 20 },
        maxLevel: 3,
        basePrice: 180,
        priceScale: 2.0,
        requires: { unlock_vers_bolt: 1 },
    },
    {
        id: 'sonic_pierce',
        title: 'Gjennomtrengende Sang',
        icon: 'item_spear',
        category: 'Kvad',
        classRestriction: 'skald',
        shopCategoryId: 'skald_fiolin',
        chapterId: 'foundation',
        summary: 'Stridssang går gjennom fiender',
        value: { prefix: '+', suffix: ' pierce', getValue: (lvl) => lvl },
        maxLevel: 3,
        basePrice: 250,
        priceScale: 2.5,
        requires: { sonic_damage: 1 },
    },
    {
        id: 'kvad_radius',
        title: 'Kvasets Rekkevidde',
        icon: 'item_panflute',
        category: 'Kvad',
        classRestriction: 'skald',
        shopCategoryId: 'skald_kvad',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Øker rekkevidden til Panfløyte',
        value: { prefix: '+', suffix: 'px', getValue: (lvl) => lvl * 30 },
        maxLevel: 3,
        basePrice: 280,
        priceScale: 2.4,
        iconTint: 'drop-shadow(0 0 5px #d4a017) hue-rotate(30deg)',
        requires: { unlock_kvad_seier: 1 },
    },
    {
        id: 'kvad_duration',
        title: 'Langvarig Kvad',
        icon: 'item_moon_crescent',
        category: 'Kvad',
        classRestriction: 'skald',
        shopCategoryId: 'skald_horn',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Øker varigheten på Horn',
        value: { prefix: '+', suffix: ' sek', getValue: (lvl) => lvl },
        maxLevel: 3,
        basePrice: 250,
        priceScale: 2.3,
        iconTint: 'drop-shadow(0 0 5px #d4a017) hue-rotate(30deg)',
        requires: { unlock_kvad_inspire: 1 },
    },
    {
        id: 'blodkvad',
        title: 'Blodkvad',
        icon: 'item_sword',
        category: 'Kvad',
        classRestriction: 'skald',
        shopCategoryId: 'skald_kvad',
        chapterId: 'combat_style',
        summary: 'Panfløyte gjenoppretter helse basert på skade',
        value: { suffix: '% lifesteal', getValue: (lvl) => lvl * 15 },
        maxLevel: 3,
        basePrice: 350,
        priceScale: 2.6,
        requires: { kvad_radius: 1 },
    },
    {
        id: 'krigsbarde',
        title: 'Krigsbarde',
        icon: 'item_sword_heavy',
        category: 'Kvad',
        classRestriction: 'skald',
        shopCategoryId: 'skald_kvad',
        chapterId: 'combat_style',
        summary: 'Panfløyte krever kun 4 Vers i stedet for 5',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 800,
        priceScale: 1.0,
        requires: { vers_damage: 3, kvad_radius: 2 },
        iconTint: 'drop-shadow(0 0 6px #ffd700) brightness(1.3)',
    },
    {
        id: 'ekko',
        title: 'Ekko av Kvad',
        icon: 'item_panflute',
        category: 'Kvad',
        classRestriction: 'skald',
        shopCategoryId: 'skald_kvad',
        chapterId: 'combat_style',
        summary: 'Panfløyte gjør ekstra skade over tid',
        value: { suffix: ' ekstra treff', getValue: (lvl) => lvl > 0 ? 4 : 0 },
        maxLevel: 1,
        basePrice: 600,
        priceScale: 1.0,
        requires: { kvad_radius: 2 },
        iconTint: 'drop-shadow(0 0 6px #ffd700) brightness(1.3)',
    },
];

/** Skald RYTME: Buffs, forsvar, rytme-synergier */
const SKALD_RYTME: ClassUpgradeConfig[] = [
    {
        id: 'stridssang_slow',
        title: 'Tung Sang',
        icon: 'item_harp',
        category: 'Rytme',
        classRestriction: 'skald',
        shopCategoryId: 'skald_fiolin',
        chapterId: 'foundation',
        summary: 'Stridssang bremser fiender ved treff',
        value: { suffix: ' sek slow', getValue: (lvl) => 0.5 + lvl * 0.5 },
        maxLevel: 3,
        basePrice: 220,
        priceScale: 2.2,
    },
    {
        id: 'harpe_lifesteal',
        title: 'Helbredende Harpe',
        icon: 'item_potion_red',
        category: 'Rytme',
        classRestriction: 'skald',
        shopCategoryId: 'skald_harpe',
        chapterId: 'foundation',
        summary: 'Harpe gjenoppretter helse ved treff',
        value: { prefix: '+', suffix: ' HP', getValue: (lvl) => lvl * 3 },
        maxLevel: 3,
        basePrice: 200,
        priceScale: 2.0,
    },
    {
        id: 'resonans_shield',
        title: 'Resonansskjold',
        icon: 'item_shield',
        category: 'Rytme',
        classRestriction: 'skald',
        shopCategoryId: 'skald_vers',
        chapterId: 'combat_style',
        summary: 'Ved maks Vers: midlertidig skadereduksjon',
        value: { suffix: '% reduksjon', getValue: (lvl) => lvl * 15 },
        maxLevel: 3,
        basePrice: 300,
        priceScale: 2.5,
        requires: { vers_damage: 1 },
    },
    {
        id: 'crescendo',
        title: 'Crescendo',
        icon: 'item_lute',
        category: 'Rytme',
        classRestriction: 'skald',
        shopCategoryId: 'skald_vers',
        chapterId: 'foundation',
        summary: 'Hvert Vers øker angrepshastighet',
        value: { prefix: '+', suffix: '% per vers', getValue: (lvl) => lvl * 8 },
        maxLevel: 3,
        basePrice: 280,
        priceScale: 2.4,
    },
    {
        id: 'anthem_of_fury',
        title: 'Raseriets Hymne',
        icon: 'item_sword_heavy',
        category: 'Rytme',
        classRestriction: 'skald',
        shopCategoryId: 'skald_kvad',
        chapterId: 'combat_style',
        summary: 'Panfløyte gir midlertidig skadebonus',
        value: { prefix: '+', suffix: '% skade', getValue: (lvl) => lvl * 20 },
        maxLevel: 3,
        basePrice: 350,
        priceScale: 2.6,
        requires: { crescendo: 1 },
    },
];

/** Skald FIOLIN: Stridssang-oppgraderinger og unike Violin-evner */
const SKALD_FIOLIN: ClassUpgradeConfig[] = [
    {
        id: 'skaldsang_lifesteal',
        title: 'Helbredende Melodi',
        icon: 'item_potion_red',
        category: 'Kvad',
        classRestriction: 'skald',
        shopCategoryId: 'skald_fiolin',
        chapterId: 'combat_style',
        isAbilityUpgrade: true,
        summary: 'Stridssang bolter gjenoppretter helse per treff',
        value: { prefix: '+', suffix: ' HP per treff', getValue: (lvl) => lvl * 2 },
        maxLevel: 3,
        basePrice: 240,
        priceScale: 2.2,
        requires: { sonic_damage: 1 },
    },
    {
        id: 'poetisk_lisens',
        title: 'Poetisk Lisens',
        icon: 'item_lute',
        category: 'Kvad',
        classRestriction: 'skald',
        shopCategoryId: 'skald_fiolin',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Stridssang avfyrer alltid 1 ekstra bolt per nivå uavhengig av Vers',
        value: { prefix: '+', suffix: ' garanterte bolter', getValue: (lvl) => lvl },
        maxLevel: 2,
        basePrice: 400,
        priceScale: 2.5,
        requires: { sonic_damage: 2 },
        iconTint: 'drop-shadow(0 0 6px #ffd700) brightness(1.3)',
    },
];

/** Skald HORN: Horn-evne-oppgraderinger */
const SKALD_HORN: ClassUpgradeConfig[] = [
    {
        id: 'horn_heal',
        title: 'Inspirasjonsbølge',
        icon: 'item_potion_red',
        category: 'Kvad',
        classRestriction: 'skald',
        shopCategoryId: 'skald_horn',
        chapterId: 'foundation',
        isAbilityUpgrade: true,
        summary: 'Øker helbredelsen fra Horn',
        value: { prefix: '+', suffix: ' HP', getValue: (lvl) => lvl * 15 },
        maxLevel: 3,
        basePrice: 220,
        priceScale: 2.0,
    },
    {
        id: 'horn_cooldown',
        title: 'Ekko av Inspirasjon',
        icon: 'item_moon_crescent',
        category: 'Kvad',
        classRestriction: 'skald',
        shopCategoryId: 'skald_horn',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Reduserer nedkjøling på Horn med 1 sek per nivå',
        value: { prefix: '-', suffix: ' sek', getValue: (lvl) => lvl },
        maxLevel: 3,
        basePrice: 300,
        priceScale: 2.4,
        requires: { kvad_duration: 1 },
    },
];

// ─── Ability Unlock Map ──────────────────────────────────────────────────────
// Maps unlock upgrade IDs → weapon/ability slot IDs added to `unlockedWeapons`.
export const ABILITY_UNLOCK_MAP: Record<string, string> = {
    unlock_whirlwind: 'ability_whirlwind',
    unlock_bulwark: 'ability_bulwark',
    unlock_grapple: 'ability_grapple',
    unlock_explosive: 'ability_explosive',
    unlock_vault: 'ability_vault',
    unlock_decoy: 'ability_decoy',
    unlock_frost: 'frost',
    unlock_lightning: 'lightning',
    unlock_cascade: 'ability_cascade',
    unlock_vers_bolt: 'ability_vers_bolt',
    unlock_kvad_inspire: 'ability_kvad_inspire',
    unlock_kvad_seier: 'ability_kvad_seier',
};

// ─── Ability Unlock Upgrades (12 total: 3 per class) ─────────────────────────

const KRIEGER_UNLOCKS: ClassUpgradeConfig[] = [
    {
        id: 'unlock_whirlwind',
        title: 'Lås Opp: Virvelvind',
        icon: 'item_swords_crossed',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_virvelvind',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Låser opp Virvelvind-evnen (hotkey 2)',
        value: { getValue: (lvl) => lvl > 0 ? 'Opplåst' : 'Låst' },
        maxLevel: 1,
        basePrice: 100,
        priceScale: 1,
        iconTint: 'drop-shadow(0 0 6px #ffcc00) brightness(1.3)',
    },
    {
        id: 'unlock_bulwark',
        title: 'Lås Opp: Jernmur',
        icon: 'item_shield',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_rustning',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Låser opp Jernmur-evnen (hotkey 3)',
        value: { getValue: (lvl) => lvl > 0 ? 'Opplåst' : 'Låst' },
        maxLevel: 1,
        basePrice: 250,
        priceScale: 1,
        iconTint: 'drop-shadow(0 0 6px #ffcc00) brightness(1.3)',
    },
    {
        id: 'unlock_grapple',
        title: 'Lås Opp: Kjettingkrok',
        icon: 'item_hook_chain',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_krok',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Låser opp Kjettingkrok-evnen (hotkey 4)',
        value: { getValue: (lvl) => lvl > 0 ? 'Opplåst' : 'Låst' },
        maxLevel: 1,
        basePrice: 500,
        priceScale: 1,
        iconTint: 'drop-shadow(0 0 6px #ffcc00) brightness(1.3)',
    },
];

const ARCHER_UNLOCKS: ClassUpgradeConfig[] = [
    {
        id: 'unlock_explosive',
        title: 'Lås Opp: Eksplosivt Skudd',
        icon: 'item_crossbow',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_fantombyge',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Låser opp Fantombyge-evnen (hotkey 2)',
        value: { getValue: (lvl) => lvl > 0 ? 'Opplåst' : 'Låst' },
        maxLevel: 1,
        basePrice: 100,
        priceScale: 1,
        iconTint: 'drop-shadow(0 0 6px #ffcc00) brightness(1.3)',
    },
    {
        id: 'unlock_vault',
        title: 'Lås Opp: Hopp og Byge',
        icon: 'item_lightning',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_vault',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Låser opp Hopp og Byge-evnen (hotkey 3)',
        value: { getValue: (lvl) => lvl > 0 ? 'Opplåst' : 'Låst' },
        maxLevel: 1,
        basePrice: 250,
        priceScale: 1,
        iconTint: 'drop-shadow(0 0 6px #ffcc00) brightness(1.3)',
    },
    {
        id: 'unlock_decoy',
        title: 'Lås Opp: Skyggemannekeng',
        icon: 'item_phantom',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_decoy',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Låser opp Skyggemannekeng-evnen (hotkey 4)',
        value: { getValue: (lvl) => lvl > 0 ? 'Opplåst' : 'Låst' },
        maxLevel: 1,
        basePrice: 500,
        priceScale: 1,
        iconTint: 'drop-shadow(0 0 6px #ffcc00) brightness(1.3)',
    },
];

const WIZARD_UNLOCKS: ClassUpgradeConfig[] = [
    {
        id: 'unlock_frost',
        title: 'Lås Opp: Frostmagi',
        icon: 'item_frost_orb',
        category: 'Magi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_frost',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Låser opp Froststav-våpenet (hotkey 2)',
        value: { getValue: (lvl) => lvl > 0 ? 'Opplåst' : 'Låst' },
        maxLevel: 1,
        basePrice: 100,
        priceScale: 1,
        iconTint: 'drop-shadow(0 0 6px #ffcc00) brightness(1.3)',
    },
    {
        id: 'unlock_lightning',
        title: 'Lås Opp: Tordenmagi',
        icon: 'item_lightning_staff',
        category: 'Magi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_torden',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Låser opp Lynstav-våpenet (hotkey 3)',
        value: { getValue: (lvl) => lvl > 0 ? 'Opplåst' : 'Låst' },
        maxLevel: 1,
        basePrice: 250,
        priceScale: 1,
        iconTint: 'drop-shadow(0 0 6px #ffcc00) brightness(1.3)',
    },
    {
        id: 'unlock_cascade',
        title: 'Lås Opp: Kaskade',
        icon: 'item_magic_staff',
        category: 'Magi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_kaskade',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Låser opp Arcane Cascade-evnen (hotkey 4)',
        value: { getValue: (lvl) => lvl > 0 ? 'Opplåst' : 'Låst' },
        maxLevel: 1,
        basePrice: 500,
        priceScale: 1,
        iconTint: 'drop-shadow(0 0 6px #ffcc00) brightness(1.3)',
    },
];

const SKALD_UNLOCKS: ClassUpgradeConfig[] = [
    {
        id: 'unlock_vers_bolt',
        title: 'Lås Opp: Stridssang',
        icon: 'item_lute',
        category: 'Kvad',
        classRestriction: 'skald',
        shopCategoryId: 'skald_fiolin',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Låser opp Stridssang-evnen (hotkey 2)',
        value: { getValue: (lvl) => lvl > 0 ? 'Opplåst' : 'Låst' },
        maxLevel: 1,
        basePrice: 100,
        priceScale: 1,
        iconTint: 'drop-shadow(0 0 6px #ffcc00) brightness(1.3)',
    },
    {
        id: 'unlock_kvad_inspire',
        title: 'Lås Opp: Horn',
        icon: 'item_moon_crescent',
        category: 'Kvad',
        classRestriction: 'skald',
        shopCategoryId: 'skald_horn',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Låser opp Horn-inspirasjon (hotkey 3)',
        value: { getValue: (lvl) => lvl > 0 ? 'Opplåst' : 'Låst' },
        maxLevel: 1,
        basePrice: 250,
        priceScale: 1,
        iconTint: 'drop-shadow(0 0 6px #ffcc00) brightness(1.3)',
    },
    {
        id: 'unlock_kvad_seier',
        title: 'Lås Opp: Seierskvad',
        icon: 'item_panflute',
        category: 'Kvad',
        classRestriction: 'skald',
        shopCategoryId: 'skald_kvad',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Låser opp Seierskvad-evnen (hotkey 4)',
        value: { getValue: (lvl) => lvl > 0 ? 'Opplåst' : 'Låst' },
        maxLevel: 1,
        basePrice: 500,
        priceScale: 1,
        iconTint: 'drop-shadow(0 0 6px #ffcc00) brightness(1.3)',
    },
];

// ─── MASTERY UPGRADES ────────────────────────────────────────────────────────
// Dyre, spillstilsendrende "mastery"-oppgraderinger. maxLevel 1, høye prerequisites.
// Bruker eksisterende sprites/partikler (tint, scale, glow, trails) — ingen nye assets.

const KRIEGER_MASTERY: ClassUpgradeConfig[] = [
    // ── Slot 1: Sverd ──
    {
        id: 'destroyer_blade',
        title: 'Ødeleggerens Klinge',
        icon: 'item_sword_heavy',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_sverd',
        chapterId: 'synergy',
        summary: 'Hvert 5. sverdtreff utløser en shockwave',
        detailedDescription: 'Hvert 5. sverdtreff utløser en kraftig shockwave-ring som gjør 200% skade i 150px radius og knockbacker alle fiender. Posisjonér deg i klynger for å maksimere effekten. Teller nullstilles ikke ved våpenbytte.',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 2000,
        priceScale: 1.0,
        requires: { damage: 8, heavy_momentum: 3 },
        iconTint: 'drop-shadow(0 0 8px #ff4400) brightness(1.4) hue-rotate(-10deg)',
    },
    {
        id: 'blood_blade',
        title: 'Blodsverd',
        icon: 'item_sword',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_sverd',
        chapterId: 'synergy',
        summary: 'Under 30% HP: 3x sverdskade + brann',
        detailedDescription: 'Når du er under 30% HP gjør sverdangrep 3x skade og setter fiender i brann. Over 30% HP: normal skade. Drep med sverdet gjenoppretter 5% av maks HP. Kombinerer kraftig med Berserkerfurie for ekstrem lav-HP skade.',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 2500,
        priceScale: 1.0,
        requires: { berserker_rage: 3, livsstaling: 3 },
        iconTint: 'drop-shadow(0 0 8px #cc0000) brightness(1.4)',
    },
    {
        id: 'mirror_blade',
        title: 'Speilklinge',
        icon: 'item_shield',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_sverd',
        chapterId: 'synergy',
        summary: 'Lagrer skade du tar, slipper ut som AoE',
        detailedDescription: '40% av all skade du tar de neste 3 sekundene etter et sverdtreff lagres opp. Neste sverdtreff slipper ut all lagret skade som en AoE-eksplosjon (150px radius). Jo mer du blir truffet mellom slag, jo kraftigere blir neste slag.',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 2500,
        priceScale: 1.0,
        requires: { armor: 5, counter_strike: 3 },
        iconTint: 'drop-shadow(0 0 8px #cc44ff) brightness(1.4) hue-rotate(200deg)',
    },
    // ── Slot 2: Virvelvind ──
    {
        id: 'eternal_storm',
        title: 'Evig Storm',
        icon: 'item_swords_crossed',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_virvelvind',
        chapterId: 'synergy',
        isAbilityUpgrade: true,
        summary: '2x varighet, bevegelig dødsaura',
        detailedDescription: 'Virvelvind varer dobbelt så lenge, og du kan bevege deg med 50% fart mens den er aktiv. Endrer virvelvind fra en kortvarig burst til en vedvarende dødsaura du navigerer med gjennom slagfeltet.',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 2000,
        priceScale: 1.0,
        requires: { whirl_damage: 3, whirl_cooldown: 3 },
        iconTint: 'drop-shadow(0 0 10px #ff2200) brightness(1.5) hue-rotate(-15deg)',
    },
    {
        id: 'splinter_storm',
        title: 'Splinterstorm',
        icon: 'item_swords_crossed',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_virvelvind',
        chapterId: 'synergy',
        isAbilityUpgrade: true,
        summary: 'Virvelvind sender ut 8 piercende prosjektiler',
        detailedDescription: 'Ved aktivering av virvelvind sendes 8 prosjektiler ut i alle retninger. Prosjektilene gjør 50% av virvelvind-skade og piercer 2 fiender. Gjør virvelvind til et hybrid ranged/melee-verktøy perfekt for å rydde rom.',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 2000,
        priceScale: 1.0,
        requires: { whirl_chain: 2 },
        iconTint: 'drop-shadow(0 0 10px #ff6600) brightness(1.5) hue-rotate(-10deg)',
    },
    // ── Slot 3: Jernmur ──
    {
        id: 'thorn_fortress',
        title: 'Tornerustning',
        icon: 'item_shield',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_rustning',
        chapterId: 'synergy',
        summary: 'Jernmur reflekterer blokkert skade som AoE',
        detailedDescription: 'Mens Jernmur er aktiv reflekteres all skade du blokkerer som AoE-skade (150px radius) rundt deg. Stå i midten av en horde med Jernmur aktiv og la dem drepe seg selv. Mer skade du tar = mer reflektert skade.',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 2500,
        priceScale: 1.0,
        requires: { fortification: 3, blodust: 3 },
        iconTint: 'drop-shadow(0 0 10px #ff4400) brightness(1.5)',
    },
    {
        id: 'gravity_wall',
        title: 'Gravitasjonsmur',
        icon: 'item_shield',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_rustning',
        chapterId: 'synergy',
        summary: 'Jernmur suger fiender inn + eksplosiv avslutning',
        detailedDescription: 'Jernmur suger inn alle fiender innenfor 200px mot deg. Når Jernmur avsluttes: eksplosiv knockback som sender dem vekk. Pull fiender inn, avslutt Jernmur, og bruk virvelvind/sverd på den sammenklumpede horden.',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 2500,
        priceScale: 1.0,
        requires: { iron_will: 1, skadeskalering: 3 },
        iconTint: 'drop-shadow(0 0 10px #8800ff) brightness(1.5) hue-rotate(200deg)',
    },
    // ── Slot 4: Kjettingkrok ──
    {
        id: 'lava_chain',
        title: 'Lavakjetting',
        icon: 'item_hook_chain',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_krok',
        chapterId: 'synergy',
        isAbilityUpgrade: true,
        summary: 'Krok etterlater brannfelt langs banen',
        detailedDescription: 'Kjettingkroken etterlater et brannfelt langs hele banen den reiser. Feltet varer 4 sekunder og gjør kontinuerlig skade. Dratte fiender tar ekstra brennskade. Perfekt for zone-kontroll — del opp slagfeltet med brannlinjer.',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 2000,
        priceScale: 1.0,
        requires: { grapple_damage: 3, grapple_chain: 1 },
        iconTint: 'drop-shadow(0 0 10px #ff6600) brightness(1.5) hue-rotate(-20deg)',
    },
    {
        id: 'soul_grapple',
        title: 'Sjelelenke',
        icon: 'item_hook_chain',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_krok',
        chapterId: 'synergy',
        isAbilityUpgrade: true,
        summary: 'Kobler deg til fiende: lifesteal + dødseksplosjon',
        detailedDescription: 'Krok kobler deg til fienden med en sjelelenke i 5 sekunder. All skade du gjør mot den lenkede fienden healer deg 30%. Hvis fienden dør mens lenket: AoE-eksplosjon (200px) som skader alle rundt. Velg ut en tøff fiende og tank gjennom kampen.',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 2500,
        priceScale: 1.0,
        requires: { grapple_lifesteal: 2, grapple_stun: 1 },
        iconTint: 'drop-shadow(0 0 10px #cc00ff) brightness(1.5) hue-rotate(240deg)',
    },
];

const ARCHER_MASTERY: ClassUpgradeConfig[] = [
    // ── Slot 1: Bue ──
    {
        id: 'solar_curse',
        title: 'Solforbannelse',
        icon: 'item_bow',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_bue',
        chapterId: 'synergy',
        summary: '3 treff på samme fiende = eksplosjon',
        detailedDescription: 'Piler markerer fiender med en sol-rune. Etter 3 markeringer på samme fiende: automatisk eksplosjon (180px radius, gullfarget). Markører varer 5 sekunder. Belønner fokus-fire mot enkeltmål fremfor spray.',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 2000,
        priceScale: 1.0,
        requires: { arrow_damage: 5, explosive_arrow: 3 },
        iconTint: 'drop-shadow(0 0 10px #ffcc00) brightness(1.5) hue-rotate(30deg)',
    },
    {
        id: 'wind_arrows',
        title: 'Vindpiler',
        icon: 'item_bow',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_bue',
        chapterId: 'synergy',
        summary: 'Piler gjennom bevegelsessti = 2x fart, +50% skade',
        detailedDescription: 'Din bevegelse etterlater en usynlig vindsti (2 sekunder). Piler som passerer gjennom stien akselererer til dobbel fart og gjør +50% skade. Kiting blir et våpen — løp, snu, skyt gjennom din egen vindsti.',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 2000,
        priceScale: 1.0,
        requires: { arrow_speed: 5, eagle_eye: 3 },
        iconTint: 'drop-shadow(0 0 10px #00ccff) brightness(1.5) hue-rotate(160deg)',
    },
    {
        id: 'splinter_arrow',
        title: 'Splitterpil',
        icon: 'item_crossbow',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_bue',
        chapterId: 'synergy',
        summary: 'Piler splitter i 3 søkende mini-piler ved treff',
        detailedDescription: 'Piler som treffer en fiende splitter seg i 3 mini-piler som søker andre fiender innen 200px. Mini-pilene gjør 40% skade. Anti-horde: skyt inn i en klynge og se pilene finne egne mål. Synergerer godt med multishot.',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 2500,
        priceScale: 1.0,
        requires: { multishot: 4, pierce: 2 },
        iconTint: 'drop-shadow(0 0 10px #33ff33) brightness(1.5) hue-rotate(80deg)',
    },
    // ── Slot 2: Fantombyge ──
    {
        id: 'fate_volley',
        title: 'Skjebnesalve',
        icon: 'item_crossbow',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_fantombyge',
        chapterId: 'synergy',
        isAbilityUpgrade: true,
        summary: 'Fantombyge homer mot fiender, stacking skade',
        detailedDescription: 'Fantombyge-piler søker mot fiender automatisk. Piler som treffer samme fiende gjør +25% skade per pil (stacking). Boss-dreper: aktivér og alle piler graviterer mot nærmeste store trussel for massiv akkumulert skade.',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 2000,
        priceScale: 1.0,
        requires: { volley_damage: 3, volley_count: 3 },
        iconTint: 'drop-shadow(0 0 10px #ff6600) brightness(1.5) hue-rotate(20deg)',
    },
    {
        id: 'hail_storm',
        title: 'Haglstorm',
        icon: 'item_crossbow',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_fantombyge',
        chapterId: 'synergy',
        isAbilityUpgrade: true,
        summary: 'Fantombyge skaper frostfelt ved treff',
        detailedDescription: 'Fantombyge-piler skaper midlertidige frostfelt (300px område) ved treff. Fiender i feltet bremses 50% i 3 sekunder. Endrer Fantombyge fra direkte skade til AoE-kontroll — perfekt for å sette opp frost-feller.',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 2500,
        priceScale: 1.0,
        requires: { volley_pierce: 2, frost_trap: 2 },
        iconTint: 'drop-shadow(0 0 10px #00aaff) brightness(1.5) hue-rotate(180deg)',
    },
    // ── Slot 3: Vault ──
    {
        id: 'shadow_vault',
        title: 'Skyggespranget',
        icon: 'item_lightning',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_vault',
        chapterId: 'synergy',
        isAbilityUpgrade: true,
        summary: 'Hopp etterlater giftsky + forgifter piler',
        detailedDescription: 'Hoppet etterlater en giftig røyk-sky der du stod (4 sekunder, DoT). Fiender i skyen får redusert aggro-rekkevidde. Vault-piler forgiftes automatisk. Hit-and-run ekspert: hopp, etterlat gift, skyt trygt.',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 2000,
        priceScale: 1.0,
        requires: { vault_damage: 3, vault_distance: 3 },
        iconTint: 'drop-shadow(0 0 10px #33ff33) brightness(1.5) hue-rotate(80deg)',
    },
    {
        id: 'double_vault',
        title: 'Dobbeltspranget',
        icon: 'item_lightning',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_vault',
        chapterId: 'synergy',
        isAbilityUpgrade: true,
        summary: 'Vault kan brukes 2x på rad (360° piler på 2.)',
        detailedDescription: 'Du kan aktivere Vault to ganger innen 2 sekunder (andre hopp er gratis). Andre hoppet sender ut piler i 360 grader i stedet for vifte. Begge hopp gir i-frames. Ultra-mobilitet: nesten umulig å treffe.',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 2500,
        priceScale: 1.0,
        requires: { vault_cooldown: 3, vault_arrows: 3 },
        iconTint: 'drop-shadow(0 0 10px #88ccff) brightness(1.5) hue-rotate(160deg)',
    },
    // ── Slot 4: Decoy ──
    {
        id: 'doppelganger',
        title: 'Dobbeltgjenger',
        icon: 'item_phantom',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_decoy',
        chapterId: 'synergy',
        isAbilityUpgrade: true,
        summary: 'Klone som skyter + teleport ved død',
        detailedDescription: 'Lokkefuglen kopierer dine angrep og skyter piler mot nærmeste fiende (50% skade). Hvis fiender ødelegger lokkefuglen: du teleporteres til dens posisjon (blink-effekt). Strategisk klone for kryssilding + escape.',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 2000,
        priceScale: 1.0,
        requires: { decoy_mimic: 1, decoy_invis: 3 },
        iconTint: 'drop-shadow(0 0 10px #aa55ff) brightness(1.5) hue-rotate(240deg)',
    },
    {
        id: 'trap_network',
        title: 'Sprengfelle-Nett',
        icon: 'item_phantom',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_decoy',
        chapterId: 'synergy',
        isAbilityUpgrade: true,
        summary: '3 mini-lokkefugler som kjedeeksploderer',
        detailedDescription: 'Plasserer 3 mini-lokkefugler (0.5x størrelse) i stedet for 1 stor. Når en fiende kommer nær en: alle 3 detonerer samtidig i kjedeeksplosjon (kombinert 400px radius). Minelegger: plasser feller langs fiende-ruter.',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 2500,
        priceScale: 1.0,
        requires: { decoy_explode: 1, decoy_duration: 3 },
        iconTint: 'drop-shadow(0 0 10px #ff4400) brightness(1.5) hue-rotate(-10deg)',
    },
];

const WIZARD_MASTERY: ClassUpgradeConfig[] = [
    // ── Slot 1: Ildkule ──
    {
        id: 'solar_flare',
        title: 'Solflare',
        icon: 'item_magic_staff',
        category: 'Magi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_ild',
        chapterId: 'synergy',
        summary: 'Ildkule etterlater brennende sti',
        detailedDescription: 'Ildkulen etterlater en brennende sti langs hele banen. Stien varer 3 sekunder og gjør DoT. Skyt gjennom korridorer av fiender — banen blir like farlig som eksplosjonen. Synergerer med splash-radius-oppgraderinger.',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 2000,
        priceScale: 1.0,
        requires: { fire_damage: 5, fire_chain: 3 },
        iconTint: 'drop-shadow(0 0 10px #ff6600) brightness(1.5) hue-rotate(-15deg)',
    },
    {
        id: 'unstable_core',
        title: 'Ustabil Kjerne',
        icon: 'item_magic_staff',
        category: 'Magi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_ild',
        chapterId: 'synergy',
        summary: 'Ildkule vokser over avstand (0.6x→2.5x)',
        detailedDescription: 'Ildkulen vokser i størrelse over avstand (1x → 3x scale). Maks-størrelse gjør 2.5x skade med 2x eksplosjonsradius. Kort-distanse treff er svakere (0.6x). Avstandsspiller: belønner deg for å holde avstand.',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 2000,
        priceScale: 1.0,
        requires: { fire_radius: 3, massiv_eksplosjon: 2 },
        iconTint: 'drop-shadow(0 0 10px #ffaa00) brightness(1.5) hue-rotate(10deg)',
    },
    {
        id: 'chain_omega',
        title: 'Kjedereaksjon Ω',
        icon: 'item_magic_staff',
        category: 'Magi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_ild',
        chapterId: 'synergy',
        summary: 'Drap utløser nye ildkuler → kaskade',
        detailedDescription: 'Ildkule-eksplosjoner som dreper en fiende utløser automatisk 2 nye ildkuler (0.7x scale) mot nærmeste fiender. Disse kan også trigger chain. Maks 3 generasjoner. Horde-ødelegger: ett godt skudd kaskader gjennom hele skjermen.',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 2500,
        priceScale: 1.0,
        requires: { fire_chain: 3, fire_speed: 5 },
        iconTint: 'drop-shadow(0 0 12px #ff2200) brightness(1.6) hue-rotate(-20deg)',
    },
    // ── Slot 2: Frost ──
    {
        id: 'ice_prison',
        title: 'Iskrystall-Fengsel',
        icon: 'item_frost_orb',
        category: 'Magi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_frost',
        chapterId: 'synergy',
        summary: 'Drepte frosne fiender kjedefryser naboer',
        detailedDescription: 'Frosne fiender som dør eksploderer i iskrystaller (120px radius) som fryser alle nærliggende fiender. Kjedefrysing kan spre seg opptil 3 ganger. Frys én, drep den, se frostbølgen spre seg gjennom horden.',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 2000,
        priceScale: 1.0,
        requires: { frost_shatter: 3, frost_radius: 3 },
        iconTint: 'drop-shadow(0 0 10px #00ddff) brightness(1.5) hue-rotate(180deg)',
    },
    {
        id: 'frost_domain',
        title: 'Absolutt Frostfelt',
        icon: 'item_frost_orb',
        category: 'Magi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_frost',
        chapterId: 'synergy',
        summary: 'Frost-cast lager permanent frostfelt (maks 3)',
        detailedDescription: 'Frost-cast legger igjen et permanent frostfelt (200px radius, varer til neste wave). Fiender i feltet er 40% bremset og tar +25% skade fra alle kilder. Maks 3 felt aktive. Kontrollspiller: lag kill zones strategisk.',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 2500,
        priceScale: 1.0,
        requires: { frost_slow: 5, frost_radius: 3 },
        iconTint: 'drop-shadow(0 0 12px #0088ff) brightness(1.6) hue-rotate(190deg)',
    },
    // ── Slot 3: Lyn ──
    {
        id: 'thunder_storm',
        title: 'Tordenstorm',
        icon: 'item_lightning_staff',
        category: 'Magi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_torden',
        chapterId: 'synergy',
        summary: 'Treff markerer posisjon → forsinket lynnedslag',
        detailedDescription: 'Lyn som treffer en fiende markerer posisjonen. Etter 1 sekund: lynnedslag fra himmelen på alle markerte posisjoner (3x lyn-skade, 100px radius, screen shake). Maks 5 markører. Planlegg angrep — merk mål og vent på den massive oppfølgeren.',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 2000,
        priceScale: 1.0,
        requires: { lightning_damage: 5, lightning_stun: 3 },
        iconTint: 'drop-shadow(0 0 10px #ffff00) brightness(1.5) hue-rotate(40deg)',
    },
    {
        id: 'supercharge',
        title: 'Overladning Ultima',
        icon: 'item_lightning_staff',
        category: 'Magi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_torden',
        chapterId: 'synergy',
        summary: '5 lynkast = superladed mega-lyn',
        detailedDescription: 'Etter 5 lynnedslag uten å bytte våpen: neste lyn er superladed — 3x størrelse, 5x bounces, 2x skade, og etterlater statiske felt ved hvert bounce-punkt. Bli værende på lyn-våpenet for å bygge opp en katastrofal kjede.',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 2500,
        priceScale: 1.0,
        requires: { lightning_bounces: 3, lightning_voltage: 3 },
        iconTint: 'drop-shadow(0 0 12px #aaffff) brightness(1.6) hue-rotate(160deg)',
    },
    // ── Slot 4: Kaskade ──
    {
        id: 'dimension_rift',
        title: 'Dimensjonsrift',
        icon: 'item_magic_staff',
        category: 'Magi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_kaskade',
        chapterId: 'synergy',
        isAbilityUpgrade: true,
        summary: 'Kaskade teleporterer fiender til sentrum + 3x eksplosjon',
        detailedDescription: 'Kaskaden teleporterer de 3 nærmeste fiendene til sentrum hvert sekund (instant reposisjonering). Slutteksplosjonen gjør 3x skade. Boss-killer: tvinger fiender til sentrum, umulig å rømme, massiv finisher.',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 2500,
        priceScale: 1.0,
        requires: { cascade_damage: 2, cascade_radius: 3 },
        iconTint: 'drop-shadow(0 0 12px #ffffff) brightness(1.6) hue-rotate(0deg)',
    },
    {
        id: 'elemental_convergence',
        title: 'Elementær Konvergens',
        icon: 'item_magic_staff',
        category: 'Magi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_kaskade',
        chapterId: 'synergy',
        isAbilityUpgrade: true,
        summary: 'Kaskade forsterker alle trolldommer (men gjør 0 skade selv)',
        detailedDescription: 'Mens Kaskade er aktiv forsterkes alle trolldommer: ildkuler +50% radius, frost +50% slow-varighet, lyn +3 bounces. Kaskaden selv gjør INGEN skade, men blir en kraftig buff-plattform. Aktiver Kaskade → spam trolldommer for massiv forsterkelse.',
        purchaseWarning: 'ADVARSEL: Denne oppgraderingen fjerner ALL skade fra Arcane Cascade. Kaskade blir en ren buff-plattform som forsterker andre trolldommer. Vil du fortsette?',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 3000,
        priceScale: 1.0,
        requires: { cascade_duration: 3, elementar_overfload: 3 },
        iconTint: 'drop-shadow(0 0 14px #ff00ff) brightness(1.7) hue-rotate(270deg)',
    },
];

const SKALD_MASTERY: ClassUpgradeConfig[] = [
    // ── Slot 1: Harpe ──
    {
        id: 'harmonic_echo',
        title: 'Harmoni-Ekkokammer',
        icon: 'item_harp',
        category: 'Kvad',
        classRestriction: 'skald',
        shopCategoryId: 'skald_harpe',
        chapterId: 'synergy',
        summary: 'Hvert 3. treff spawner bouncing ekkobolt',
        detailedDescription: 'Hvert 3. harpe-treff utløser en ekkobolt som bouncer mellom fiender (75% skade). Ekkoen bygger Vers. Raskere vers-bygging + AoE — belønner konstant harpe-spam mot grupper av fiender.',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 2000,
        priceScale: 1.0,
        requires: { harpe_damage: 3, harpe_pierce: 2 },
        iconTint: 'drop-shadow(0 0 10px #aaddff) brightness(1.5) hue-rotate(200deg)',
    },
    {
        id: 'resonance_frequency',
        title: 'Resonansfrekvens',
        icon: 'item_harp',
        category: 'Kvad',
        classRestriction: 'skald',
        shopCategoryId: 'skald_harpe',
        chapterId: 'synergy',
        summary: 'Gjentatte treff på samme fiende eskalerer (opptil 3x)',
        detailedDescription: 'Harpe-bolter som treffer samme fiende innen 2 sekunder gjør eskalerende skade: 1. treff = 100%, 2. = 150%, 3. = 225%, 4.+ = 300%. Fienden glør sterkere for hvert treff. Fokus-fire ekspert, spesielt mot bosser.',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 2000,
        priceScale: 1.0,
        requires: { harpe_speed: 3, harpe_damage: 3 },
        iconTint: 'drop-shadow(0 0 10px #ffaa00) brightness(1.5) hue-rotate(30deg)',
    },
    // ── Slot 2: Stridssang ──
    {
        id: 'war_melody',
        title: 'Krigsmelodi',
        icon: 'item_lute',
        category: 'Kvad',
        classRestriction: 'skald',
        shopCategoryId: 'skald_fiolin',
        chapterId: 'synergy',
        summary: 'Treff gir +25% skade-debuff, drap = AoE',
        detailedDescription: 'Stridssang-bolter setter fienden i "dissonans" (+25% skade tatt, 3 sek). Fiender som dør i dissonans utløser en AoE-eksplosjon (100px, lilla). Debuff-maskin: merk fiender med Stridssang, bytt til Harpe for å utnytte økt skade.',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 2000,
        priceScale: 1.0,
        requires: { sonic_damage: 3, sonic_pierce: 3 },
        iconTint: 'drop-shadow(0 0 10px #cc00ff) brightness(1.5) hue-rotate(270deg)',
    },
    {
        id: 'ballad_curse',
        title: 'Balladens Forbannelse',
        icon: 'item_lute',
        category: 'Kvad',
        classRestriction: 'skald',
        shopCategoryId: 'skald_fiolin',
        chapterId: 'synergy',
        summary: 'Lenker fiender — deler 30% skade',
        detailedDescription: 'Stridssang-treff lenker fiender med gull-linjer. Alle lenkede fiender deler 30% av skaden de tar. Maks 5 fiender lenket, varer 6 sekunder. Horde-knuser: lenk 5 fiender, fokuser skade på én, og alle tar splash-skade.',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 2500,
        priceScale: 1.0,
        requires: { stridssang_slow: 3, sonic_damage: 3 },
        iconTint: 'drop-shadow(0 0 12px #ffd700) brightness(1.6) hue-rotate(20deg)',
    },
    // ── Slot 3: Horn ──
    {
        id: 'valkyrie_hymn',
        title: 'Valkyrje-Hymne',
        icon: 'item_moon_crescent',
        category: 'Kvad',
        classRestriction: 'skald',
        shopCategoryId: 'skald_horn',
        chapterId: 'synergy',
        isAbilityUpgrade: true,
        summary: 'Horn gir 3-treff skjold → eksplosjon med lagret skade',
        detailedDescription: 'Horn gir i tillegg et kraftskjold som absorberer de neste 3 treffene fullstendig (0 skade). Etter alle 3 treff: eksplosjon (150px) som gjør skade lik total absorbert skade. Offensiv buffer: kast deg inn, absorber treff, eksploder dem tilbake.',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 2500,
        priceScale: 1.0,
        requires: { horn_heal: 3, kvad_duration: 3 },
        iconTint: 'drop-shadow(0 0 12px #ffd700) brightness(1.6) hue-rotate(10deg)',
    },
    {
        id: 'war_horn_echo',
        title: 'Krigsropets Ekko',
        icon: 'item_moon_crescent',
        category: 'Kvad',
        classRestriction: 'skald',
        shopCategoryId: 'skald_horn',
        chapterId: 'synergy',
        isAbilityUpgrade: true,
        summary: 'Horn pulserer AoE-skade hvert 2. sek',
        detailedDescription: 'Horn-effekten pulserer AoE-skade (150px) hvert 2. sekund rundt deg. Hver puls gjør mer skade jo flere Vers du har (+10% per Vers). Proximity-damage aura: hold deg nær fiender mens Horn er aktiv.',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 2000,
        priceScale: 1.0,
        requires: { horn_cooldown: 3, crescendo: 3 },
        iconTint: 'drop-shadow(0 0 10px #ff6600) brightness(1.5) hue-rotate(-10deg)',
    },
    // ── Slot 4: Panfløyte ──
    {
        id: 'ragnarok_requiem',
        title: 'Ragnarök-Requiem',
        icon: 'item_panflute',
        category: 'Kvad',
        classRestriction: 'skald',
        shopCategoryId: 'skald_kvad',
        chapterId: 'synergy',
        isAbilityUpgrade: true,
        summary: 'Drepte fiender gjenoppstår som allierte (3 sek)',
        detailedDescription: 'Seierskvad er forsterket: 2x radius, 1.5x skade. Alle fiender drept av Seierskvad gjenoppstår som midlertidige allierte (3 sek, grønn glød) som jager andre fiender (50% skade). Nuclear option: bruk i stor horde — de døde rydder resten.',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 3000,
        priceScale: 1.0,
        requires: { kvad_radius: 3, ekko: 1 },
        iconTint: 'drop-shadow(0 0 14px #33ff33) brightness(1.7) hue-rotate(80deg)',
    },
    {
        id: 'eternal_verse',
        title: 'Evig Vers',
        icon: 'item_panflute',
        category: 'Kvad',
        classRestriction: 'skald',
        shopCategoryId: 'skald_kvad',
        chapterId: 'synergy',
        isAbilityUpgrade: true,
        summary: 'Seierskvad koster 3 Vers, gir permanent skadebonus',
        detailedDescription: 'Seierskvad koster 3 Vers (ikke 5), men gjør kun 60% skade. Til gjengjeld: alle Vers du bygger de neste 10 sekundene gir +5% permanent skadebonus (maks 10 stacks per runde). Farming-maskin: spam Seierskvad for vedvarende bonuser.',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 2500,
        priceScale: 1.0,
        requires: { krigsbarde: 1, vers_damage: 3 },
        iconTint: 'drop-shadow(0 0 12px #ffd700) brightness(1.6) hue-rotate(20deg)',
    },
];

// ─── Exported Array ───────────────────────────────────────────────────────────

export const CLASS_UPGRADES: ClassUpgradeConfig[] = [
    // ABILITY UNLOCKS (must come first so they appear at top of categories)
    ...KRIEGER_UNLOCKS,
    ...ARCHER_UNLOCKS,
    ...WIZARD_UNLOCKS,
    ...SKALD_UNLOCKS,
    // KRIEGER
    ...KRIEGER_DRIVKRAFT,
    ...KRIEGER_MASTRING_NYE,
    ...KRIEGER_KAMPTALENT,
    ...KRIEGER_RUSTNING,
    ...KRIEGER_KROK,
    // ARCHER
    ...ARCHER_DRIVKRAFT,
    ...ARCHER_TALENTER,
    ...ARCHER_VAULT,
    ...ARCHER_DECOY,
    ...ARCHER_SMIDIGHET,
    // WIZARD
    ...WIZARD_DRIVKRAFT,
    ...WIZARD_SYNERGI,
    ...WIZARD_MASTRING_NYE,
    ...WIZARD_ARKAN,
    // SKALD
    ...SKALD_KVAD,
    ...SKALD_RYTME,
    ...SKALD_FIOLIN,
    ...SKALD_HORN,
    // MASTERY (dyre, spillstilsendrende oppgraderinger)
    ...KRIEGER_MASTERY,
    ...ARCHER_MASTERY,
    ...WIZARD_MASTERY,
    ...SKALD_MASTERY,
];
