/**
 * CLASS-EXCLUSIVE UPGRADES
 * Fase 1: Alle nye upgrades som BARE én klasse kan kjøpe.
 *
 * Extends UpgradeConfig med:
 *   classRestriction: ClassId   – alltid satt (aldri undefined her)
 *   isAbilityUpgrade?: boolean  – true = påvirker class-ability direkte
 *
 * Kategorier per klasse:
 *   Krieger  → DRIVKRAFT / MASTRING / KAMPTALENT / RUSTNING
 *   Archer   → DRIVKRAFT / MASTRING / TALENTER / SMIDIGHET
 *   Wizard   → DRIVKRAFT / MASTRING / SYNERGI / ARKAN KUNNSKAP
 */

import type { UpgradeConfig } from './upgrades';
import type { ClassId } from './classes';

export interface ClassUpgradeConfig extends UpgradeConfig {
    classRestriction: ClassId;
    isAbilityUpgrade?: boolean;
    shopCategoryId: string;
}

// ─── KRIEGER ─────────────────────────────────────────────────────────────────

/** Krieger SVERD: Whirlwind Slash ability-nivåer + legendaries */
const KRIEGER_DRIVKRAFT: ClassUpgradeConfig[] = [
    {
        id: 'whirl_damage',
        title: 'Skarpe Kniver',
        icon: 'item_sword',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_sverd',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Øker skaden til virvelvind',
        value: { suffix: '%', getValue: (lvl) => 100 + lvl * 25 },
        maxLevel: 3,
        basePrice: 200,
        priceScale: 2.2,
        iconTint: 'drop-shadow(0 0 5px #cc4400) hue-rotate(-10deg)',
    },
    {
        id: 'whirl_cooldown',
        title: 'Rotasjonsfart',
        icon: 'item_swords_crossed',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_sverd',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Reduserer ventetid på virvelvind',
        value: { suffix: 's', isReduction: true, getValue: (lvl) => [6.4, 5.1, 4.1][lvl - 1] ?? 8 },
        maxLevel: 3,
        basePrice: 250,
        priceScale: 2.5,
        iconTint: 'drop-shadow(0 0 5px #cc4400) hue-rotate(-10deg)',
        requires: { whirl_damage: 1 },
    },
    {
        id: 'whirl_chain',
        title: 'Eksplosiv Sekvens',
        icon: 'item_swords_crossed',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_sverd',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Treff med virvelvind reduserer ventetid ytterligere',
        value: { prefix: '-', suffix: '% CD', getValue: (lvl) => lvl === 1 ? 25 : 35 },
        maxLevel: 2,
        basePrice: 500,
        priceScale: 2.8,
        iconTint: 'drop-shadow(0 0 5px #cc4400) hue-rotate(-10deg)',
        requires: { whirl_cooldown: 2 },
    },
    {
        id: 'berserker_rage',
        title: 'Berserkerfurie',
        icon: 'item_sword_heavy',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_sverd',
        chapterId: 'combat_style',
        summary: 'Gjør mer skade når du har lav helse',
        value: { prefix: '+', suffix: '% skade', getValue: (lvl) => lvl * 5 },
        maxLevel: 3,
        basePrice: 300,
        priceScale: 2.5,
        iconTint: 'drop-shadow(0 0 5px #cc4400) hue-rotate(-10deg)',
    },
    {
        id: 'livsstaling',
        title: 'Livsstaling',
        icon: 'item_potion_red',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_sverd',
        chapterId: 'combat_style',
        summary: 'Gjenoppretter helse ved fiendedrap i nærkamp',
        value: { prefix: '+', suffix: ' HP', getValue: (lvl) => lvl * 8 },
        maxLevel: 4,
        basePrice: 200,
        priceScale: 2.0,
    },
    {
        id: 'blodust',
        title: 'Blodtorne',
        icon: 'item_shield',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_sverd',
        chapterId: 'combat_style',
        summary: 'Returnerer deler av skaden til fienden',
        value: { suffix: '% retur', getValue: (lvl) => lvl * 15 },
        maxLevel: 3,
        basePrice: 350,
        priceScale: 2.8,
        requires: { armor: 3 },
    },
];

/** Krieger SVERD – Grunnlag (ekstra) */
const KRIEGER_MASTRING_NYE: ClassUpgradeConfig[] = [
    {
        id: 'wide_swing',
        title: 'Bred Svingning',
        icon: 'item_sword',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_sverd',
        chapterId: 'foundation',
        summary: 'Øker rekkevidden på sverdangrep',
        value: { prefix: '+', suffix: '% bue', getValue: (lvl) => lvl * 30 },
        maxLevel: 3,
        basePrice: 180,
        priceScale: 2.0,
    },
    {
        id: 'heavy_momentum',
        title: 'Tyngdekraft',
        icon: 'item_sword_heavy',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_sverd',
        chapterId: 'foundation',
        summary: 'Hvert treff øker skaden på neste slag',
        value: { prefix: '+', suffix: '% skade', getValue: (lvl) => lvl * 10 },
        maxLevel: 3,
        basePrice: 250,
        priceScale: 2.3,
    },
];

/** Krieger SVERD – Kampstil */
const KRIEGER_KAMPTALENT: ClassUpgradeConfig[] = [
    {
        id: 'counter_strike',
        title: 'Kontraangrep',
        icon: 'item_swords_crossed',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_sverd',
        chapterId: 'combat_style',
        summary: 'Sjanse for å returnere skade ved treff',
        value: { prefix: '+', suffix: '% sjanse', getValue: (lvl) => lvl * 20 },
        maxLevel: 3,
        basePrice: 300,
        priceScale: 2.5,
        requires: { armor: 2 },
    },
    {
        id: 'stomp',
        title: 'Stormtramp',
        icon: 'item_sword_heavy',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_sverd',
        chapterId: 'combat_style',
        summary: 'Etter dash: mini-AoE stun rundt spilleren',
        value: { suffix: ' sek', getValue: (lvl) => lvl === 1 ? 0.5 : 0.8 },
        maxLevel: 2,
        basePrice: 400,
        priceScale: 3.0,
        requires: { dash_cooldown: 2 },
    },
    {
        id: 'battle_cry',
        title: 'Krigsrop',
        icon: 'item_swords_crossed',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_sverd',
        chapterId: 'combat_style',
        summary: 'Drap trigger midlertidig skadebonus',
        value: { prefix: '+', suffix: '% skade', getValue: (lvl) => lvl * 15 },
        maxLevel: 3,
        basePrice: 280,
        priceScale: 2.4,
    },
    {
        id: 'executioner',
        title: 'Bøddel',
        icon: 'item_sword',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_sverd',
        chapterId: 'combat_style',
        summary: 'Økt skade mot fiender med lav helse',
        value: { prefix: '+', suffix: '% skade', getValue: (lvl) => lvl * 50 },
        maxLevel: 2,
        basePrice: 450,
        priceScale: 2.8,
        requires: { damage: 5 },
    },
];

/** Krieger RUSTNING – Defense-synergier */
const KRIEGER_RUSTNING: ClassUpgradeConfig[] = [
    {
        id: 'skadeskalering',
        title: 'Skadeskalering',
        icon: 'item_shield',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_rustning',
        chapterId: 'combat_style',
        summary: 'Øker skade basert på rustning',
        value: { prefix: '+', suffix: '% skade', getValue: (lvl) => lvl * 5 },
        maxLevel: 3,
        basePrice: 220,
        priceScale: 2.2,
        requires: { armor: 3 },
    },
    {
        id: 'utstotbar_slag',
        title: 'Utstøtbar Slag',
        icon: 'item_sword_heavy',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_rustning',
        chapterId: 'combat_style',
        summary: 'Fiender som blir dyttet bort skader hverandre',
        value: { suffix: '% eks.skade', getValue: (lvl) => lvl > 0 ? 40 : 0 },
        maxLevel: 2,
        basePrice: 500,
        priceScale: 3.0,
        requires: { knockback: 5 },
    },
    {
        id: 'iron_will',
        title: 'Jernvilje',
        icon: 'item_shield',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_rustning',
        chapterId: 'foundation',
        summary: 'Overlev dødelig skade med 1 HP',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 800,
        priceScale: 1.0,
        requires: { armor: 6 },
        iconTint: 'drop-shadow(0 0 6px #aaccff) brightness(1.3)',
    },
    {
        id: 'fortification',
        title: 'Befestning',
        icon: 'item_shield',
        category: 'Sverd',
        classRestriction: 'krieger',
        shopCategoryId: 'krieger_rustning',
        chapterId: 'combat_style',
        summary: 'Stå stille for rustningsbonus (avtar over tid)',
        value: { prefix: '+', suffix: '% rustning', getValue: (lvl) => lvl * 20 },
        maxLevel: 3,
        basePrice: 200,
        priceScale: 2.0,
    },
];

// ─── ARCHER ──────────────────────────────────────────────────────────────────

/** Archer BUE: Phantom Volley ability-nivåer + presisjon */
const ARCHER_DRIVKRAFT: ClassUpgradeConfig[] = [
    {
        id: 'volley_count',
        title: 'Pilregn',
        icon: 'item_bow',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_bue',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Øker antall piler i Fantombyge',
        value: { prefix: '+', suffix: ' piler', getValue: (lvl) => lvl * 5 },
        maxLevel: 3,
        basePrice: 220,
        priceScale: 2.3,
        iconTint: 'drop-shadow(0 0 5px #ff6600) hue-rotate(20deg)',
    },
    {
        id: 'volley_damage',
        title: 'Fantomkraft',
        icon: 'item_spear',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_bue',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Øker skaden til hver pil i Fantombyge',
        value: { suffix: 'x skade', getValue: (lvl) => (1.0 + lvl * 0.2).toFixed(1) },
        maxLevel: 3,
        basePrice: 250,
        priceScale: 2.5,
        iconTint: 'drop-shadow(0 0 5px #ff6600) hue-rotate(20deg)',
        requires: { volley_count: 1 },
    },
    {
        id: 'volley_pierce',
        title: 'Nådeløs Byge',
        icon: 'item_spear',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_bue',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Piler fra Fantombyge går gjennom flere fiender',
        value: { prefix: '+', suffix: ' pierce', getValue: (lvl) => lvl },
        maxLevel: 2,
        basePrice: 550,
        priceScale: 3.0,
        iconTint: 'drop-shadow(0 0 5px #ff6600) hue-rotate(20deg)',
        requires: { volley_damage: 2 },
    },
    {
        id: 'rikosjett',
        title: 'Rikosjett',
        icon: 'item_bow',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_bue',
        chapterId: 'combat_style',
        summary: 'Piler spretter til nye mål',
        value: { suffix: ' mål', getValue: (lvl) => lvl },
        maxLevel: 3,
        basePrice: 300,
        priceScale: 2.5,
    },
    {
        id: 'fokusert_skudd',
        title: 'Fokusert Skudd',
        icon: 'item_bow',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_bue',
        chapterId: 'combat_style',
        summary: 'Lad bue for kraftigere piercende skudd',
        value: { suffix: 'x skade', getValue: (lvl) => lvl === 1 ? 2.0 : 2.5 },
        maxLevel: 2,
        basePrice: 500,
        priceScale: 2.8,
        requires: { arrow_damage: 4 },
    },
    {
        id: 'shadeskudd',
        title: 'Skuddkaskade',
        icon: 'item_bow',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_bue',
        chapterId: 'combat_style',
        summary: 'Eksplosjons-drap genererer ekstra piler',
        value: { suffix: ' piler', getValue: (lvl) => lvl },
        maxLevel: 3,
        basePrice: 280,
        priceScale: 2.3,
        requires: { multishot: 2 },
    },
];

/** Archer BUE – Presisjon (talenter) */
const ARCHER_TALENTER: ClassUpgradeConfig[] = [
    {
        id: 'headshot',
        title: 'Hodeskudd',
        icon: 'item_bow',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_bue',
        chapterId: 'combat_style',
        summary: 'Økt sjanse for kritiske treff med piler',
        value: { prefix: '+', suffix: '% sjanse', getValue: (lvl) => lvl * 15 },
        maxLevel: 3,
        basePrice: 200,
        priceScale: 2.2,
        requires: { crit_chance: 2 },
    },
    {
        id: 'eagle_eye',
        title: 'Ørneøye',
        icon: 'item_bow',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_bue',
        chapterId: 'combat_style',
        summary: 'Øker pilhastighet og rekkevidde',
        value: { prefix: '+', suffix: '% fart', getValue: (lvl) => lvl * 30 },
        maxLevel: 3,
        basePrice: 250,
        priceScale: 2.4,
        requires: { arrow_speed: 3 },
    },
    {
        id: 'pindown',
        title: 'Festepil',
        icon: 'item_spear',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_bue',
        chapterId: 'combat_style',
        summary: 'Sjanse for at piler stopper fiender',
        value: { suffix: ' sek', getValue: (lvl) => 0.5 + lvl },
        maxLevel: 3,
        basePrice: 350,
        priceScale: 2.7,
        requires: { pierce: 1 },
    },
    {
        id: 'time_slow_arrow',
        title: 'Tempopil',
        icon: 'item_bow',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_bue',
        chapterId: 'combat_style',
        summary: 'Spesialpil som bremser alle fiender',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 700,
        priceScale: 1.0,
        requires: { eagle_eye: 2 },
        iconTint: 'drop-shadow(0 0 6px #00ccff) hue-rotate(160deg)',
    },
];

/** Archer SMIDIGHET – Mobilitet */
const ARCHER_SMIDIGHET: ClassUpgradeConfig[] = [
    {
        id: 'luftmobilitet',
        title: 'Luftmobilitet',
        icon: 'item_lightning',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_smidighet',
        summary: 'Øker antall tilgjengelige dash',
        value: { suffix: ' totalt', getValue: (lvl) => 2 + lvl },
        maxLevel: 2,
        basePrice: 350,
        priceScale: 3.0,
    },
    {
        id: 'aerial_shot',
        title: 'Luftskudd',
        icon: 'item_bow',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_smidighet',
        summary: 'Mulighet til å skyte under dash uten fartsreduksjon',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 2,
        basePrice: 300,
        priceScale: 2.8,
    },
    {
        id: 'shadow_step',
        title: 'Skyggetrinn',
        icon: 'item_lightning',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_smidighet',
        summary: 'Midlertidig usynlighet etter dash',
        value: { suffix: ' sek', getValue: (lvl) => lvl === 1 ? 0.5 : 1 },
        maxLevel: 2,
        basePrice: 400,
        priceScale: 3.0,
    },
    {
        id: 'kite_mastery',
        title: 'Dragemanøver',
        icon: 'item_lightning',
        category: 'Bue',
        classRestriction: 'archer',
        shopCategoryId: 'archer_smidighet',
        summary: 'Drap reduserer ventetid på dash umiddelbart',
        value: { prefix: '-', suffix: '% CD', getValue: (lvl) => lvl * 20 },
        maxLevel: 3,
        basePrice: 220,
        priceScale: 2.2,
    },
];

// ─── WIZARD ──────────────────────────────────────────────────────────────────

/** Wizard EVNER: Arcane Cascade ability-nivåer + legendaries */
const WIZARD_DRIVKRAFT: ClassUpgradeConfig[] = [
    {
        id: 'cascade_duration',
        title: 'Mørk Materie',
        icon: 'item_magic_staff',
        category: 'Magi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_evner',
        isAbilityUpgrade: true,
        summary: 'Øker varigheten på Arcane Cascade',
        value: { suffix: ' sek', getValue: (lvl: number) => 3 + lvl * 0.5 },
        maxLevel: 3,
        basePrice: 250,
        priceScale: 2.4,
        iconTint: 'drop-shadow(0 0 5px #8800ff) hue-rotate(200deg)',
    },
    {
        id: 'cascade_radius',
        title: 'Hendelseshorisont',
        icon: 'item_magic_staff',
        category: 'Magi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_evner',
        isAbilityUpgrade: true,
        summary: 'Øker draradius til Arcane Cascade',
        value: { prefix: '+', suffix: '%', getValue: (lvl: number) => lvl * 25 },
        maxLevel: 3,
        basePrice: 280,
        priceScale: 2.5,
        iconTint: 'drop-shadow(0 0 5px #8800ff) hue-rotate(200deg)',
        requires: { cascade_duration: 1 },
    },
    {
        id: 'cascade_damage',
        title: 'Knusende Gravitasjon',
        icon: 'item_lightning_staff',
        category: 'Magi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_evner',
        isAbilityUpgrade: true,
        summary: 'Eksplosjonen gjør mer skade i sentrum',
        value: { prefix: '+', suffix: '%', getValue: (lvl: number) => lvl * 50 },
        maxLevel: 2,
        basePrice: 600,
        priceScale: 3.0,
        iconTint: 'drop-shadow(0 0 5px #8800ff) hue-rotate(200deg)',
        requires: { cascade_radius: 2 },
    },
    {
        id: 'manaring',
        title: 'Manaring',
        icon: 'item_frost_orb',
        category: 'Magi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_evner',
        summary: 'Aktiv Kaskade gir skadereduksjon',
        value: { suffix: '%', getValue: (lvl: number) => lvl === 1 ? 25 : 40 },
        maxLevel: 2,
        basePrice: 450,
        priceScale: 2.8,
        requires: { cascade_duration: 2 },
    },
    {
        id: 'elementar_overfload',
        title: 'Elementær Overflod',
        icon: 'item_magic_staff',
        category: 'Magi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_evner',
        summary: 'Bruk av trolldom øker skaden til andre trolldommer',
        value: { prefix: '+', suffix: '% skade', getValue: (lvl) => lvl * 10 },
        maxLevel: 3,
        basePrice: 320,
        priceScale: 2.6,
    },
    {
        id: 'nullifikasjon',
        title: 'Magisk Nullifikasjon',
        icon: 'item_frost_orb',
        category: 'Magi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_evner',
        summary: 'Egen trolldom kan ødelegge innkommende bolter',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 900,
        priceScale: 1.0,
        requires: { cascade_damage: 1 },
        iconTint: 'drop-shadow(0 0 8px #8800ff) hue-rotate(200deg) brightness(1.3)',
    },
];

/** Wizard SYNERGI – Trolldomsinteraksjoner */
const WIZARD_SYNERGI: ClassUpgradeConfig[] = [
    {
        id: 'frozen_lightning',
        title: 'Frosset Torden',
        icon: 'item_lightning_staff',
        category: 'Synergi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_synergi',
        summary: 'Frosne fiender truffet av lyn splintres',
        value: { prefix: 'x', suffix: ' skade', getValue: (lvl) => lvl > 0 ? 4 : 1 },
        maxLevel: 1,
        basePrice: 700,
        priceScale: 1.0,
        requires: { frost_shatter: 2, lightning_stun: 3 },
        iconTint: 'drop-shadow(0 0 6px #8800ff) hue-rotate(200deg)',
    },
    {
        id: 'blaze_storm',
        title: 'Ildstorm',
        icon: 'item_magic_staff',
        category: 'Synergi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_synergi',
        summary: 'Kombinasjon av ild og lyn lager midlertidig brannfelt',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 2,
        basePrice: 600,
        priceScale: 2.5,
        requires: { fire_chain: 2, lightning_damage: 5 },
        iconTint: 'drop-shadow(0 0 6px #8800ff) hue-rotate(200deg)',
    },
    {
        id: 'absolute_zero',
        title: 'Absolutt Null',
        icon: 'item_frost_orb',
        category: 'Synergi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_synergi',
        summary: 'Frosne fiender kan kastes mot andre fiender',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 1000,
        priceScale: 1.0,
        requires: { frost_slow: 5, cascade_duration: 2 },
        iconTint: 'drop-shadow(0 0 6px #8800ff) hue-rotate(200deg)',
    },
];

/** Wizard ILDMAGI – Ekstra massiv eksplosjon */
const WIZARD_MASTRING_NYE: ClassUpgradeConfig[] = [
    {
        id: 'massiv_eksplosjon',
        title: 'Massiv Eksplosjon',
        icon: 'item_magic_staff',
        category: 'Magi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_ild',
        summary: 'Større rekkevidde på ildkuler',
        value: { prefix: '+', suffix: 'px radius', getValue: (lvl) => lvl * 40 },
        maxLevel: 2,
        basePrice: 500,
        priceScale: 2.5,
    },
];

/** Wizard EVNER – Avanserte trolldomsteknikker */
const WIZARD_ARKAN: ClassUpgradeConfig[] = [
    {
        id: 'spell_echo',
        title: 'Trolldomseko',
        icon: 'item_magic_staff',
        category: 'Magi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_evner',
        summary: 'Sjanse for å kaste trolldom uten ventetid',
        value: { suffix: '% sjanse', getValue: (lvl) => lvl * 15 },
        maxLevel: 3,
        basePrice: 300,
        priceScale: 2.5,
    },
    {
        id: 'overload',
        title: 'Overbelastning',
        icon: 'item_lightning_staff',
        category: 'Magi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_evner',
        summary: 'Treffer 3 fiender gir gratis neste kast',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 2,
        basePrice: 400,
        priceScale: 2.8,
        requires: { spell_echo: 2 },
    },
    {
        id: 'arcane_insight',
        title: 'Arkan Innsikt',
        icon: 'item_magic_staff',
        category: 'Magi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_evner',
        summary: 'Hvert 4. kast reduserer ventetid på trolldom',
        value: { prefix: '-', suffix: '% CD', getValue: (lvl) => lvl * 30 },
        maxLevel: 3,
        basePrice: 350,
        priceScale: 2.6,
    },
    {
        id: 'mana_shield',
        title: 'Manadel',
        icon: 'item_frost_orb',
        category: 'Magi',
        classRestriction: 'wizard',
        shopCategoryId: 'wizard_evner',
        summary: 'Sjanse for å absorbere skade med ventetid-reduksjon',
        value: { prefix: '+', suffix: '% sjanse', getValue: (lvl) => lvl * 30 },
        maxLevel: 2,
        basePrice: 500,
        priceScale: 3.0,
        requires: { armor: 2 },
    },
];

// ─── SKALD ───────────────────────────────────────────────────────────────────

/** Skald KVAD: Vers-skalering, Stridssang, Kvad-utbrudd */
const SKALD_KVAD: ClassUpgradeConfig[] = [
    {
        id: 'vers_damage',
        title: 'Versets Kraft',
        icon: 'item_lute',
        category: 'Kvad',
        classRestriction: 'skald',
        shopCategoryId: 'skald_kvad',
        chapterId: 'foundation',
        summary: 'Hvert Vers øker skaden',
        value: { prefix: '+', suffix: '% per vers', getValue: (lvl) => lvl * 15 },
        maxLevel: 3,
        basePrice: 200,
        priceScale: 2.2,
    },
    {
        id: 'sonic_damage',
        title: 'Stridssangens Kraft',
        icon: 'item_harp',
        category: 'Kvad',
        classRestriction: 'skald',
        shopCategoryId: 'skald_kvad',
        chapterId: 'foundation',
        summary: 'Øker skaden til Stridssang',
        value: { prefix: '+', suffix: '% skade', getValue: (lvl) => lvl * 20 },
        maxLevel: 3,
        basePrice: 180,
        priceScale: 2.0,
    },
    {
        id: 'sonic_pierce',
        title: 'Gjennomtrengende Sang',
        icon: 'item_spear',
        category: 'Kvad',
        classRestriction: 'skald',
        shopCategoryId: 'skald_kvad',
        chapterId: 'foundation',
        summary: 'Stridssang går gjennom fiender',
        value: { prefix: '+', suffix: ' pierce', getValue: (lvl) => lvl },
        maxLevel: 3,
        basePrice: 250,
        priceScale: 2.5,
        requires: { sonic_damage: 1 },
    },
    {
        id: 'kvad_radius',
        title: 'Kvasets Rekkevidde',
        icon: 'item_panflute',
        category: 'Kvad',
        classRestriction: 'skald',
        shopCategoryId: 'skald_kvad',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Øker rekkevidden til Seierskvad',
        value: { prefix: '+', suffix: 'px', getValue: (lvl) => lvl * 30 },
        maxLevel: 3,
        basePrice: 280,
        priceScale: 2.4,
        iconTint: 'drop-shadow(0 0 5px #d4a017) hue-rotate(30deg)',
    },
    {
        id: 'kvad_duration',
        title: 'Langvarig Kvad',
        icon: 'item_harp',
        category: 'Kvad',
        classRestriction: 'skald',
        shopCategoryId: 'skald_kvad',
        chapterId: 'ability',
        isAbilityUpgrade: true,
        summary: 'Øker varigheten på Inspirerende Kvad',
        value: { prefix: '+', suffix: ' sek', getValue: (lvl) => lvl },
        maxLevel: 3,
        basePrice: 250,
        priceScale: 2.3,
        iconTint: 'drop-shadow(0 0 5px #d4a017) hue-rotate(30deg)',
    },
    {
        id: 'poetisk_lisens',
        title: 'Poetisk Lisens',
        icon: 'item_lute',
        category: 'Kvad',
        classRestriction: 'skald',
        shopCategoryId: 'skald_kvad',
        chapterId: 'combat_style',
        summary: 'Bryt rytmen uten å miste Vers (kort nådetid)',
        value: { suffix: ' sek nåde', getValue: (lvl) => lvl === 1 ? 0.5 : 1.0 },
        maxLevel: 2,
        basePrice: 400,
        priceScale: 2.8,
        requires: { vers_damage: 2 },
    },
    {
        id: 'blodkvad',
        title: 'Blodkvad',
        icon: 'item_sword',
        category: 'Kvad',
        classRestriction: 'skald',
        shopCategoryId: 'skald_kvad',
        chapterId: 'combat_style',
        summary: 'Seierskvad gjenoppretter helse basert på skade',
        value: { suffix: '% lifesteal', getValue: (lvl) => lvl * 15 },
        maxLevel: 3,
        basePrice: 350,
        priceScale: 2.6,
        requires: { kvad_radius: 1 },
    },
    {
        id: 'krigsbarde',
        title: 'Krigsbarde',
        icon: 'item_sword_heavy',
        category: 'Kvad',
        classRestriction: 'skald',
        shopCategoryId: 'skald_kvad',
        chapterId: 'combat_style',
        summary: 'Seierskvad krever kun 3 Vers i stedet for 4',
        value: { getValue: (lvl) => lvl > 0 ? 'Aktiv' : 'Låst' },
        maxLevel: 1,
        basePrice: 800,
        priceScale: 1.0,
        requires: { vers_damage: 3, kvad_radius: 2 },
        iconTint: 'drop-shadow(0 0 6px #ffd700) brightness(1.3)',
    },
    {
        id: 'ekko',
        title: 'Ekko av Kvad',
        icon: 'item_panflute',
        category: 'Kvad',
        classRestriction: 'skald',
        shopCategoryId: 'skald_kvad',
        chapterId: 'combat_style',
        summary: 'Seierskvad gjør ekstra skade over tid',
        value: { suffix: ' ekstra treff', getValue: (lvl) => lvl > 0 ? 4 : 0 },
        maxLevel: 1,
        basePrice: 600,
        priceScale: 1.0,
        requires: { kvad_radius: 2 },
        iconTint: 'drop-shadow(0 0 6px #ffd700) brightness(1.3)',
    },
];

/** Skald RYTME: Buffs, forsvar, rytme-synergier */
const SKALD_RYTME: ClassUpgradeConfig[] = [
    {
        id: 'stridssang_slow',
        title: 'Tung Sang',
        icon: 'item_harp',
        category: 'Rytme',
        classRestriction: 'skald',
        shopCategoryId: 'skald_rytme',
        summary: 'Stridssang bremser fiender ved treff',
        value: { suffix: ' sek slow', getValue: (lvl) => 0.5 + lvl * 0.5 },
        maxLevel: 3,
        basePrice: 220,
        priceScale: 2.2,
    },
    {
        id: 'skaldsang_lifesteal',
        title: 'Helbredende Vers',
        icon: 'item_potion_red',
        category: 'Rytme',
        classRestriction: 'skald',
        shopCategoryId: 'skald_rytme',
        summary: 'Korrekt rytme-treff gjenoppretter helse',
        value: { prefix: '+', suffix: ' HP', getValue: (lvl) => lvl * 5 },
        maxLevel: 3,
        basePrice: 200,
        priceScale: 2.0,
    },
    {
        id: 'resonans_shield',
        title: 'Resonansskjold',
        icon: 'item_shield',
        category: 'Rytme',
        classRestriction: 'skald',
        shopCategoryId: 'skald_rytme',
        summary: 'Ved maks Vers: midlertidig skadereduksjon',
        value: { suffix: '% reduksjon', getValue: (lvl) => lvl * 15 },
        maxLevel: 3,
        basePrice: 300,
        priceScale: 2.5,
        requires: { vers_damage: 1 },
    },
    {
        id: 'crescendo',
        title: 'Crescendo',
        icon: 'item_lute',
        category: 'Rytme',
        classRestriction: 'skald',
        shopCategoryId: 'skald_rytme',
        summary: 'Hvert Vers øker angrepshastighet',
        value: { prefix: '+', suffix: '% per vers', getValue: (lvl) => lvl * 8 },
        maxLevel: 3,
        basePrice: 280,
        priceScale: 2.4,
    },
    {
        id: 'anthem_of_fury',
        title: 'Raseriets Hymne',
        icon: 'item_sword_heavy',
        category: 'Rytme',
        classRestriction: 'skald',
        shopCategoryId: 'skald_rytme',
        summary: 'Seierskvad gir midlertidig skadebonus',
        value: { prefix: '+', suffix: '% skade', getValue: (lvl) => lvl * 20 },
        maxLevel: 3,
        basePrice: 350,
        priceScale: 2.6,
        requires: { crescendo: 1 },
    },
];

// ─── Exported Array ───────────────────────────────────────────────────────────

export const CLASS_UPGRADES: ClassUpgradeConfig[] = [
    // KRIEGER
    ...KRIEGER_DRIVKRAFT,
    ...KRIEGER_MASTRING_NYE,
    ...KRIEGER_KAMPTALENT,
    ...KRIEGER_RUSTNING,
    // ARCHER
    ...ARCHER_DRIVKRAFT,
    ...ARCHER_TALENTER,
    ...ARCHER_SMIDIGHET,
    // WIZARD
    ...WIZARD_DRIVKRAFT,
    ...WIZARD_SYNERGI,
    ...WIZARD_MASTRING_NYE,
    ...WIZARD_ARKAN,
    // SKALD
    ...SKALD_KVAD,
    ...SKALD_RYTME,
];
